export const tracks = [
  {
    album: null,
    artists: "Bayza, Dimatis",
    cover: "sojourn",
    dark: false,
    date: "2024-08-30 00:00:00",
    description: null,
    duration: "3:21",
    fanlink: "lnk.bayzamusic.com/Sojourn",
    fanlinks: {
      "amazon": null,
      "amazon-music": null,
      "anghami": "https://play.anghami.com/song/1175428217",
      "apple": "https://music.apple.com/us/album/sojourn-single/1766377012?app=music&ls=1",
      "bandcamp": null,
      "beatport": null,
      "deezer": "https://www.deezer.com/en/album/638066901",
      "download": null,
      "itunes": "https://music.apple.com/us/album/sojourn-single/1766377012?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/sojourn",
      "spotify": "https://open.spotify.com/track/3Q7z3tRpsC8WgbK8lUsNoH?si",
      "tidal": null,
      "tiktok": null,
      "vk": null,
      "yandex": null,
      "youtube": "https://www.youtube.com/watch?v=Rq0tw63-JjU"
    },
    genre: "Chill",
    id: "sojourn",
    image: "/images/releases/2024/sojourn.jpg",
    label: null,
    title: "Sojourn",
    type: "Releases",
    video: "Rq0tw63-JjU",
    year: 2024
  },
  {
    album: null,
    artists: "Bayza",
    cover: "redemption",
    dark: false,
    date: "2024-05-17 00:00:00",
    description: null,
    duration: "2:48",
    fanlink: "lnk.bayzamusic.com/Redemption",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0D37GQGL8",
      "amazon-music": "https://music.amazon.com/albums/B0D37GQGL8",
      "anghami": "https://play.anghami.com/song/1158016182",
      "apple": "https://music.apple.com/us/album/redemption-single/1744520806?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/redemption/19085038?lang=en",
      "deezer": "https://www.deezer.com/en/album/581442682",
      "download": null,
      "itunes": "https://music.apple.com/us/album/redemption-single/1744520806?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/redemption",
      "spotify": "https://open.spotify.com/track/67pgxQVCfkKlb6MF4XZwgt?si",
      "tidal": "https://tidal.com/browse/album/361089939",
      "tiktok": "https://www.tiktok.com/music/Redemption-7364730359069165569",
      "vk": "https://vk.com/audio-2001517820_127517820",
      "yandex": "https://music.yandex.com/album/31037673",
      "youtube": "https://www.youtube.com/watch?v=bk_08D0S2fI"
    },
    genre: "Dance",
    id: "redemption",
    image: "/images/releases/2024/redemption.jpg",
    label: null,
    title: "Redemption",
    type: "Releases",
    video: "bk_08D0S2fI",
    year: 2024
  },
  {
    album: null,
    artists: "Bayza",
    cover: "obsession",
    dark: false,
    date: "2023-09-8 00:00:00",
    description: null,
    duration: "2:45",
    fanlink: "lnk.bayzamusic.com/Obsession",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0CF5S8YT2",
      "amazon-music": "https://music.amazon.com/albums/B0CF5S8YT2",
      "anghami": "https://play.anghami.com/song/1120936709",
      "apple": "https://music.apple.com/us/album/obsession-single/1701788265?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/obsession/18023565",
      "deezer": "https://www.deezer.com/en/album/474309635",
      "download": null,
      "itunes": "https://music.apple.com/us/album/obsession-single/1701788265?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/miss-deepshine/bayza-obsession",
      "spotify": "https://open.spotify.com/track/5pPZ45aI9CtT7baMS4HVUs?si",
      "tidal": "https://tidal.com/browse/album/309926493",
      "tiktok": "https://www.tiktok.com/music/Obsession-7265380182788950017",
      "vk": "https://vk.com/audio-2001859002_121859002",
      "yandex": "https://music.yandex.com/album/26916071?lang=en",
      "youtube": "https://www.youtube.com/watch?v=KNmD8d2bnp0"
    },
    genre: "Deep House",
    id: "obsession",
    image: "/images/releases/2023/obsession.jpg",
    label: "DeepShine Records",
    title: "Obsession",
    type: "Releases",
    video: "KNmD8d2bnp0",
    year: 2023
  },
  {
    album: null,
    artists: "Bayza",
    cover: "now-or-never",
    dark: false,
    date: "2023-08-11 00:00:00",
    description: null,
    duration: "2:36",
    fanlink: "lnk.bayzamusic.com/NowOrNever",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0CC6B8KLR",
      "amazon-music": "https://music.amazon.com/albums/B0CC6B8KLR",
      "anghami": "https://play.anghami.com/song/1118122446",
      "apple": "https://music.apple.com/us/album/now-or-never-single/1698143831?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/now-or-never/17952075",
      "deezer": "https://www.deezer.com/en/album/465827855",
      "download": null,
      "itunes": "https://music.apple.com/us/album/now-or-never-single/1698143831?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/miss-deepshine/bayza-now-or-never",
      "spotify": "https://open.spotify.com/track/0gvM4YHMsYTeDGL8AJH3bN?si",
      "tidal": "https://tidal.com/browse/album/305471645",
      "tiktok": "https://vm.tiktok.com/ZM23JEjLf/",
      "vk": "https://vk.com/audio-2001428828_121428828",
      "yandex": "https://music.yandex.com/album/26657703?lang=en",
      "youtube": "https://www.youtube.com/watch?v=CS-AQefwkRk"
    },
    genre: "Deep House",
    id: "now-or-never",
    image: "/images/releases/2023/now-or-never.jpg",
    label: "DeepShine Records",
    title: "Now Or Never",
    type: "Releases",
    video: "CS-AQefwkRk",
    year: 2023
  },
  {
    album: "Breeze",
    artists: "Bayza",
    cover: "breeze",
    dark: false,
    date: "2023-07-28 00:00:05",
    description: null,
    duration: "2:53",
    fanlink: "lnk.bayzamusic.com/Breeze",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0CC3RZBTX",
      "amazon-music": "https://music.amazon.com/albums/B0CC3RZBTX",
      "anghami": "https://play.anghami.com/song/1117982345",
      "apple": "https://music.apple.com/us/album/breeze/1697983016?i=1697983017?app=music&ls=1",
      "bandcamp": null,
      "beatport": null,
      "deezer": "https://www.deezer.com/en/track/2371516145",
      "download": null,
      "itunes": "https://music.apple.com/us/album/breeze/1697983016?i=1697983017?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/breeze",
      "spotify": "https://open.spotify.com/track/7a995L9yBtuVlcggutehwU?si",
      "tidal": "https://tidal.com/browse/track/305333026",
      "tiktok": "https://vm.tiktok.com/ZM2sMykq7/",
      "vk": "https://vk.com/audio-2001389420_121389420",
      "yandex": "https://music.yandex.com/album/26634204/track/115585114?lang=en",
      "youtube": "https://youtu.be/vIVwrWVBA2E"
    },
    genre: "Deep House",
    id: "breeze",
    image: "/images/releases/2023/breeze.jpg",
    label: null,
    title: "Breeze",
    type: "Releases",
    video: "vIVwrWVBA2E",
    year: 2023
  },
  {
    album: "Breeze",
    artists: "Bayza",
    cover: "breeze",
    dark: false,
    date: "2023-07-28 00:00:04",
    description: null,
    duration: "3:16",
    fanlink: "lnk.bayzamusic.com/ImmortalLove",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0CC3RZBTX",
      "amazon-music": "https://music.amazon.com/albums/B0CC3RZBTX",
      "anghami": "https://play.anghami.com/song/1117982385",
      "apple": "https://music.apple.com/us/album/immortal-love/1697983016?i=1697983034?app=music&ls=1",
      "bandcamp": null,
      "beatport": null,
      "deezer": "https://www.deezer.com/en/track/2371516155",
      "download": null,
      "itunes": "https://music.apple.com/us/album/immortal-love/1697983016?i=1697983034?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/immortal-love",
      "spotify": "https://open.spotify.com/track/3vdUF4cEhnzUTKY2g336VT?si",
      "tidal": "https://tidal.com/browse/track/305333027",
      "tiktok": "https://vm.tiktok.com/ZM2sMjhU5/",
      "vk": "https://vk.com/audio-2001389419_121389419",
      "yandex": "https://music.yandex.com/album/26634204/track/115585115?lang=en",
      "youtube": "https://youtu.be/16xwnEkR8tA"
    },
    genre: "Deep House",
    id: "immortal-love",
    image: "/images/releases/2023/breeze.jpg",
    label: null,
    title: "Immortal Love",
    type: "Releases",
    video: "16xwnEkR8tA",
    year: 2023
  },
  {
    album: "Breeze",
    artists: "Bayza",
    cover: "breeze",
    dark: false,
    date: "2023-07-28 00:00:03",
    description: null,
    duration: "3:00",
    fanlink: "lnk.bayzamusic.com/Eclipse",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0CC3RZBTX",
      "amazon-music": "https://music.amazon.com/albums/B0CC3RZBTX",
      "anghami": "https://play.anghami.com/song/1117982411",
      "apple": "https://music.apple.com/us/album/eclipse/1697983016?i=1697983186?app=music&ls=1",
      "bandcamp": null,
      "beatport": null,
      "deezer": "https://www.deezer.com/en/track/2371516165",
      "download": null,
      "itunes": "https://music.apple.com/us/album/eclipse/1697983016?i=1697983186?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/eclipse",
      "spotify": "https://open.spotify.com/track/2qLanL8j4BG8Bxmbwf8KUr?si",
      "tidal": "https://tidal.com/browse/track/305333028",
      "tiktok": "https://vm.tiktok.com/ZM2sMAh8W/",
      "vk": "https://vk.com/audio-2001389418_121389418",
      "yandex": "https://music.yandex.com/album/26634204/track/115585116?lang=en",
      "youtube": "https://youtu.be/LGAtjLR89dU"
    },
    genre: "Deep House",
    id: "eclipse",
    image: "/images/releases/2023/breeze.jpg",
    label: null,
    title: "Eclipse",
    type: "Releases",
    video: "LGAtjLR89dU",
    year: 2023
  },
  {
    album: "Breeze",
    artists: "Bayza",
    cover: "breeze",
    dark: false,
    date: "2023-07-28 00:00:02",
    description: null,
    duration: "2:13",
    fanlink: "lnk.bayzamusic.com/Zenith",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0CC3RZBTX",
      "amazon-music": "https://music.amazon.com/albums/B0CC3RZBTX",
      "anghami": "https://play.anghami.com/song/1117982439",
      "apple": "https://music.apple.com/us/album/zenith/1697983016?i=1697983187?app=music&ls=1",
      "bandcamp": null,
      "beatport": null,
      "deezer": "https://www.deezer.com/en/track/2371516175",
      "download": null,
      "itunes": "https://music.apple.com/us/album/zenith/1697983016?i=1697983187?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/zenith",
      "spotify": "https://open.spotify.com/track/24gHMDA9cBPL6tkhlb9kpi?si",
      "tidal": "https://tidal.com/browse/track/305333029",
      "tiktok": "https://vm.tiktok.com/ZM2sMfvXF/",
      "vk": "https://vk.com/audio-2001389417_121389417",
      "yandex": "https://music.yandex.com/album/26634204/track/115585117?lang=en",
      "youtube": "https://youtu.be/h6rcysVZIBI"
    },
    genre: "Psytrance",
    id: "zenith",
    image: "/images/releases/2023/breeze.jpg",
    label: null,
    title: "Zenith",
    type: "Releases",
    video: "h6rcysVZIBI",
    year: 2023
  },
  {
    album: "Breeze",
    artists: "Bayza",
    cover: "breeze",
    dark: false,
    date: "2023-07-28 00:00:01",
    description: null,
    duration: "3:42",
    fanlink: "lnk.bayzamusic.com/Fiesta",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0CC3RZBTX",
      "amazon-music": "https://music.amazon.com/albums/B0CC3RZBTX",
      "anghami": "https://play.anghami.com/song/1117982477",
      "apple": "https://music.apple.com/us/album/fiesta/1697983016?i=1697983188?app=music&ls=1",
      "bandcamp": null,
      "beatport": null,
      "deezer": "https://www.deezer.com/en/track/2371516185",
      "download": null,
      "itunes": "https://music.apple.com/us/album/fiesta/1697983016?i=1697983188?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/fiesta",
      "spotify": "https://open.spotify.com/track/5TtDCIM5UtqImBmpFAgxSb?si",
      "tidal": "https://tidal.com/browse/track/305333030",
      "tiktok": "https://vm.tiktok.com/ZM2sM6V8A/",
      "vk": "https://vk.com/audio-2001389416_121389416",
      "yandex": "https://music.yandex.com/album/26634204/track/115585118?lang=en",
      "youtube": "https://youtu.be/uXM19g7wyFk"
    },
    genre: "Melbourne Bounce",
    id: "fiesta",
    image: "/images/releases/2023/breeze.jpg",
    label: null,
    title: "Fiesta",
    type: "Releases",
    video: "uXM19g7wyFk",
    year: 2023
  },
  {
    album: "Breeze",
    artists: "Bayza",
    cover: "breeze",
    dark: false,
    date: "2023-07-28 00:00:00",
    description: null,
    duration: "2:33",
    fanlink: "lnk.bayzamusic.com/Awakening",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0CC3RZBTX",
      "amazon-music": "https://music.amazon.com/albums/B0CC3RZBTX",
      "anghami": "https://play.anghami.com/song/1117982502",
      "apple": "https://music.apple.com/us/album/awakening/1697983016?i=1697983189?app=music&ls=1",
      "bandcamp": null,
      "beatport": null,
      "deezer": "https://www.deezer.com/en/track/2371516195",
      "download": null,
      "itunes": "https://music.apple.com/us/album/awakening/1697983016?i=1697983189?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/awakening",
      "spotify": "https://open.spotify.com/track/6wMJANvi2w0FLbxGfdUUWq?si",
      "tidal": "https://tidal.com/browse/track/305333031",
      "tiktok": "https://vm.tiktok.com/ZM2sMedV6/",
      "vk": "https://vk.com/audio-2001389415_121389415",
      "yandex": "https://music.yandex.com/album/26634204/track/115585119?lang=en",
      "youtube": "https://youtu.be/tSEUdjq4dzs"
    },
    genre: "Big Room",
    id: "awakening",
    image: "/images/releases/2023/breeze.jpg",
    label: null,
    title: "Awakening",
    type: "Releases",
    video: "tSEUdjq4dzs",
    year: 2023
  },
  {
    album: null,
    artists: "Bayza",
    cover: "light-comes-up",
    dark: false,
    date: "2023-05-11 00:00:00",
    description: null,
    duration: "2:49",
    fanlink: "lnk.bayzamusic.com/LightComesUp",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0C2F5KKGZ",
      "amazon-music": "https://music.amazon.com/albums/B0C2F5KKGZ",
      "anghami": "https://play.anghami.com/song/1108028422",
      "apple": "https://music.apple.com/us/album/light-comes-up-single/1682299520?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/light-comes-up/17617300",
      "deezer": "https://www.deezer.com/en/album/429628627",
      "download": null,
      "itunes": "https://music.apple.com/us/album/light-comes-up-single/1682299520?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/different-twins-records/bayza-light-comes-up-original-mix",
      "spotify": "https://open.spotify.com/track/3PZA5orGDLCDJoQfARGqfX?si",
      "tidal": "https://tidal.com/browse/album/292450765",
      "tiktok": null,
      "vk": null,
      "yandex": null,
      "youtube": "https://youtu.be/uesHdgS0o04"
    },
    genre: "Chill House",
    id: "light-comes-up",
    image: "/images/releases/2023/light-comes-up.jpg",
    label: "Twins Girls Records",
    title: "Light Comes Up",
    type: "Releases",
    video: "uesHdgS0o04",
    year: 2023
  },
  {
    album: null,
    artists: "Bayza, Staarz",
    cover: "madhouse",
    dark: false,
    date: "2023-03-10 00:00:00",
    description: null,
    duration: "2:34",
    fanlink: "lnk.bayzamusic.com/Madhouse",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0BSFWXRDP",
      "amazon-music": "https://music.amazon.com/albums/B0BSFWXRDP",
      "anghami": null,
      "apple": "https://music.apple.com/us/album/madhouse-single/1665619537?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/madhouse/17495770",
      "deezer": "https://www.deezer.com/en/album/397018667",
      "download": null,
      "itunes": "https://music.apple.com/us/album/madhouse-single/1665619537?app=itunes&ls=1",
      "soundcloud": null,
      "spotify": "https://open.spotify.com/track/0fnzxQtjDrZB7PoKkZrtRq?si",
      "tidal": "https://tidal.com/browse/album/271627779",
      "tiktok": "https://vm.tiktok.com/ZMYaBDVVL/",
      "vk": null,
      "yandex": null,
      "youtube": "https://youtu.be/Hj_kBReLOQA"
    },
    genre: "Deep House",
    id: "madhouse",
    image: "/images/releases/2023/madhouse.jpg",
    label: "The Night Drive",
    title: "Madhouse",
    type: "Releases",
    video: "Hj_kBReLOQA",
    year: 2023
  },
  {
    album: null,
    artists: "Bayza, Staarz",
    cover: "lunchbox-friends",
    dark: false,
    date: "2022-12-09 00:00:00",
    description: null,
    duration: "2:53",
    fanlink: "lnk.bayzamusic.com/LunchboxFriends",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0D27MNDNH",
      "amazon-music": "https://music.amazon.com/albums/B0D27MNDNH",
      "anghami": "https://play.anghami.com/song/1087409615",
      "apple": "https://music.apple.com/us/album/lunchbox-friends-single/1656228833?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/lunchbox-friends/17160703",
      "deezer": "https://www.deezer.com/en/album/379666247",
      "download": null,
      "itunes": "https://music.apple.com/us/album/lunchbox-friends-single/1656228833?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/lunchbox-friends",
      "spotify": "https://open.spotify.com/track/5NTgzi48ph4C6XVIQAbwh0?si",
      "tidal": "https://tidal.com/browse/album/262661229",
      "tiktok": "https://vm.tiktok.com/ZMFbtcG6P/",
      "vk": "https://vk.com/audio-2001862149_115862149",
      "yandex": "https://music.yandex.com/album/24173348",
      "youtube": "https://youtu.be/HRrD3Mj3sEY"
    },
    genre: "Deep House",
    id: "lunchbox-friends",
    image: "/images/releases/2022/lunchbox-friends.jpg",
    label: "Gangster City",
    title: "Lunchbox Friends",
    type: "Releases",
    video: "HRrD3Mj3sEY",
    year: 2022
  },
  {
    album: null,
    artists: "Bayza",
    cover: "true-lovers",
    dark: false,
    date: "2022-11-04 00:00:00",
    description: null,
    duration: "3:01",
    fanlink: "lnk.bayzamusic.com/TrueLovers",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0BKLGWWVS",
      "amazon-music": "https://music.amazon.com/albums/B0BKLGWWVS",
      "anghami": "https://play.anghami.com/song/1083050886",
      "apple": "https://music.apple.com/us/album/true-lovers-single/1651614322?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/true-lovers/17059785",
      "deezer": "https://www.deezer.com/en/album/370359407",
      "download": null,
      "itunes": "https://music.apple.com/us/album/true-lovers-single/1651614322?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/markmusic-records/bayza-true-lovers",
      "spotify": "https://open.spotify.com/track/6ef1FEoz0Cu3KHbuDSYASG?si",
      "tidal": "https://tidal.com/browse/album/256422059",
      "tiktok": "https://vm.tiktok.com/ZMFUjckkU/",
      "vk": null,
      "yandex": null,
      "youtube": "https://youtu.be/_UNJ54LGdKc"
    },
    genre: "Deep House",
    id: "true-lovers",
    image: "/images/releases/2022/true-lovers.jpg",
    label: "Mark Music Records",
    title: "True Lovers",
    type: "Releases",
    video: "_UNJ54LGdKc",
    year: 2022
  },
  {
    album: null,
    artists: "DJ Phellix, Bayza",
    cover: "on-your-mind",
    dark: true,
    date: "2022-09-01 00:00:00",
    description: null,
    duration: "2:34",
    fanlink: "lnk.bayzamusic.com/OnYourMind",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0B8QJHZ5K",
      "amazon-music": "https://music.amazon.com/albums/B0B8QJHZ5K",
      "anghami": "https://play.anghami.com/song/1074758447",
      "apple": "https://music.apple.com/gb/album/on-your-mind-single/1638166687?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/on-your-mind/16800163",
      "deezer": "https://www.deezer.com/en/album/343313487",
      "download": null,
      "itunes": "https://music.apple.com/gb/album/on-your-mind-single/1638166687?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/different-twins-records/dj-phellix-bayza-on-your-mind",
      "spotify": "https://open.spotify.com/track/23ResGtuGS7PZ8IkJY0tD6?si",
      "tidal": "https://tidal.com/browse/album/244466774",
      "tiktok": "https://vm.tiktok.com/ZMN34omnp/",
      "vk": null,
      "yandex": null,
      "youtube": "https://youtu.be/0fdvG4GRRFA"
    },
    genre: "Dance",
    id: "on-your-mind",
    image: "/images/releases/2022/on-your-mind.jpg",
    label: "Different Twins/Twin Girls Records",
    title: "On Your Mind",
    type: "Releases",
    video: "0fdvG4GRRFA",
    year: 2022
  },
  {
    album: null,
    artists: "AMiR, Bayza",
    cover: "why-cant-it-be",
    dark: false,
    date: "2022-08-05 00:00:00",
    description: null,
    duration: "2:58",
    fanlink: "lnk.bayzamusic.com/WhyCantItBe",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0B6D4357K",
      "amazon-music": "https://music.amazon.com/albums/B0B6D4357K",
      "anghami": "https://play.anghami.com/song/1068970039",
      "apple": "https://music.apple.com/gb/album/why-cant-it-be-with-me-single/1634401486?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/why-cant-it-be-with-me/16723069",
      "deezer": "https://www.deezer.com/en/album/335049457",
      "download": null,
      "itunes": "https://music.apple.com/gb/album/why-cant-it-be-with-me-single/1634401486?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/why-cant-it-be-with-me",
      "spotify": "https://open.spotify.com/track/5bobIozgIlM7WUd78pjjZk?si",
      "tidal": "https://tidal.com/browse/album/237512259",
      "tiktok": null,
      "vk": null,
      "yandex": null,
      "youtube": "https://youtu.be/BRRXzu2Q1-g"
    },
    genre: "Dance",
    id: "why-cant-it-be",
    image: "/images/releases/2022/why-cant-it-be.jpg",
    label: "Storm Music Group",
    title: "Why Can't It Be With Me",
    type: "Releases",
    video: "BRRXzu2Q1-g",
    year: 2022
  },
  {
    album: null,
    artists: "DJ Phellix, Bayza",
    cover: "young-free",
    dark: true,
    date: "2022-07-08 00:00:00",
    description: null,
    duration: "3:23",
    fanlink: "lnk.bayzamusic.com/YoungFree",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0B3N6FCWX",
      "amazon-music": "https://music.amazon.com/albums/B0B3N6FCWX",
      "anghami": "https://play.anghami.com/song/1067760636",
      "apple": "https://music.apple.com/us/album/young-free-single/1628785279?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/young-free/16625491",
      "deezer": "https://www.deezer.com/en/album/326129717",
      "download": null,
      "itunes": "https://music.apple.com/us/album/young-free-single/1628785279?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/miamibeats/dj-phellix-bayza-young-free",
      "spotify": "https://open.spotify.com/track/2EkUc71rIYQ5EL6cYlG3aQ?si",
      "tidal": "https://tidal.com/browse/album/235798699",
      "tiktok": "https://vm.tiktok.com/ZMNUstycp/",
      "vk": null,
      "yandex": null,
      "youtube": "https://youtu.be/-vVutcvq5I4"
    },
    genre: "Tropical House",
    id: "young-free",
    image: "/images/releases/2022/young-free.jpg",
    label: "Miami Beats",
    title: "Young & Free",
    type: "Releases",
    video: "-vVutcvq5I4",
    year: 2022
  },
  {
    album: null,
    artists: "dbeet, Bayza",
    cover: "show-me-what-you-feel",
    dark: false,
    date: "2022-06-10 00:00:00",
    description: null,
    duration: "2:44",
    fanlink: "lnk.bayzamusic.com/ShowMe",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0B2Z43XCD",
      "amazon-music": "https://music.amazon.com/albums/B0B2Z43XCDK",
      "anghami": "https://play.anghami.com/album/1028794041",
      "apple": "https://music.apple.com/us/album/show-me-what-you-feel-single/1627403896?app=music&ls=1",
      "bandcamp": null,
      "beatport": null,
      "deezer": "https://www.deezer.com/en/album/324225927",
      "download": null,
      "itunes": "https://music.apple.com/us/album/show-me-what-you-feel-single/1627403896?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/dbeet-sc/show-me-what-you-feel",
      "spotify": "https://open.spotify.com/track/3Qh3LiD7QhA9tja21VcbH1?si",
      "tidal": "https://tidal.com/browse/album/232005755",
      "tiktok": "https://vm.tiktok.com/ZMN8aHhwT/",
      "vk": null,
      "yandex": null,
      "youtube": "https://youtu.be/trdqaqZCVEU"
    },
    genre: "Dance",
    id: "show-me",
    image: "/images/releases/2022/show-me-what-you-feel.jpg",
    label: "Melodicity Records",
    title: "Show Me What You Feel",
    type: "Releases",
    video: "trdqaqZCVEU",
    year: 2022
  },
  {
    album: null,
    artists: "Bayza",
    cover: "pieces",
    dark: true,
    date: "2022-05-06 00:00:00",
    description: null,
    duration: "3:03",
    fanlink: "lnk.bayzamusic.com/Pieces",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B09Y9FFYCK",
      "amazon-music": "https://music.amazon.com/albums/B09Y9FFYCK",
      "anghami": "https://play.anghami.com/album/1027693271",
      "apple": "https://music.apple.com/us/album/pieces-single/1619991869?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/pieces/16547858",
      "deezer": "https://www.deezer.com/en/album/312206297",
      "download": null,
      "itunes": "https://music.apple.com/us/album/pieces-single/1619991869?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/pieces",
      "spotify": "hhttps://open.spotify.com/track/5NLKAwLStRwDM64ccfad9M?si",
      "tidal": "https://tidal.com/browse/album/225585088",
      "tiktok": "https://vm.tiktok.com/ZMLWYV8Lb/",
      "vk": null,
      "yandex": null,
      "youtube": "https://youtu.be/VTscrLkd20s"
    },
    genre: "Dance",
    id: "pieces",
    image: "/images/releases/2022/pieces.jpg",
    label: null,
    title: "Pieces",
    type: "Releases",
    video: "VTscrLkd20s",
    year: 2022
  },
  {
    album: null,
    artists: "Dimatis, Bayza",
    cover: "call-out",
    dark: false,
    date: "2022-02-25 00:00:01",
    description: null,
    duration: "3:40",
    fanlink: "lnk.bayzamusic.com/CallOut",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B09RSX8Q4V",
      "amazon-music": "https://music.amazon.com/albums/B09RSPHPFT",
      "anghami": "https://play.anghami.com/song/1042671155",
      "apple": "https://music.apple.com/us/album/call-out-single/1608543909?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/call-out/16262945",
      "deezer": "https://www.deezer.com/en/album/293077852",
      "download": null,
      "itunes": "https://music.apple.com/us/album/call-out-single/1608543909?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/dimatis/call-out",
      "spotify": "https://open.spotify.com/track/6JTB5ZwH1zW3vyBiDH9nLU?si",
      "tidal": "https://tidal.com/browse/album/215313561",
      "tiktok": "https://vm.tiktok.com/ZMLBhQ3tW",
      "vk": "https://vk.com/music/album/-2000544930_14544930",
      "yandex": "https://music.yandex.com/album/20983998",
      "youtube": "https://youtu.be/vlU7crlYW4I"
    },
    genre: "Electropop",
    id: "call-out",
    image: "/images/releases/2022/call-out.jpg",
    label: null,
    title: "Call Out",
    type: "Releases",
    video: "vlU7crlYW4I",
    year: 2022
  },
  {
    artists: "Dimatis, Bayza",
    dark: false,
    date: "2022-02-25 00:00:00",
    fanlinkId: "callout_instrumental",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B09RSKDFDP",
      "amazon-music": "https://music.amazon.com/albums/B09RSPHPFT",
      "anghami": "https://play.anghami.com/song/1042671166",
      "apple": "https://music.apple.com/us/album/call-out-instrumental/1608543909?i=1608543911?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/call-out/16262946",
      "deezer": "https://www.deezer.com/en/album/293077852",
      "download": null,
      "itunes": "https://music.apple.com/us/album/call-out-single/1608543909?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/dimatis/call-out-instrumental",
      "spotify": "https://open.spotify.com/track/3E1biqR9EGXv4fADrE6bbU?si",
      "tidal": "https://tidal.com/browse/track/215313572",
      "tiktok": "https://vm.tiktok.com/ZMLBhCxMa",
      "vk": "https://vk.com/audio-2001887791_104887791",
      "yandex": "https://music.yandex.com/album/20983998",
      "youtube": "https://youtu.be/Jg-W6hRAAxM"
    },
    image: "/images/releases/2022/call-out.jpg",
    title: "Call Out (Instrumental)"
  },
  {
    album: null,
    artists: "Bayza",
    cover: "im-falling",
    dark: false,
    date: "2022-01-21 00:00:00",
    description: null,
    duration: "3:32",
    fanlink: "lnk.bayzamusic.com/ImFalling",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B09NQBHG3T",
      "amazon-music": "https://music.amazon.com/albums/B09NQBHG3T",
      "anghami": "https://play.anghami.com/song/1038127845",
      "apple": "https://music.apple.com/us/album/im-falling-single/1600734185?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/im-falling/16068383",
      "deezer": "https://www.deezer.com/en/album/280910701",
      "download": null,
      "itunes": "https://music.apple.com/us/album/im-falling-single/1600734185?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/miss-deepshine/bayza-im-falling",
      "spotify": "https://open.spotify.com/track/2d8Pg2zA4BsR1ppWDvFvwZ?si",
      "tidal": "https://tidal.com/browse/album/209511422",
      "tiktok": "https://vm.tiktok.com/ZMLdt7P6q",
      "vk": "https://vk.com/music/album/-2000066080_14066080",
      "yandex": "https://music.yandex.com/album/20065720",
      "youtube": "https://youtu.be/EZodqty3HLA"
    },
    genre: "Deep House",
    id: "im-falling",
    image: "/images/releases/2022/im-falling.jpg",
    label: "DeepShine Records",
    title: "I'm Falling",
    type: "Releases",
    video: "EZodqty3HLA",
    year: 2022
  },
  {
    album: "Passages",
    artists: "Bayza",
    cover: "passages",
    dark: false,
    date: "2021-12-30 00:00:06",
    description: "To end the year, I decided to release an original track within an EP that also includes instrumentals of some of my previous bootlegs.",
    duration: "3:00",
    fanlink: "lnk.bayzamusic.com/Passages",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B09N644GRK",
      "amazon-music": "https://music.amazon.com/albums/B09N6DDN5X?trackAsin=B09N644GRK",
      "apple": "https://music.apple.com/us/album/passages/1600730723?i=1600730725?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/passages/16170765",
      "deezer": "https://www.deezer.com/en/track/1593460561",
      "download": null,
      "itunes": "https://music.apple.com/us/album/passages/1600730723?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/passages",
      "spotify": "https://open.spotify.com/track/4RS92LczkSL2BQaGbCwuzp?si",
      "tidal": "https://tidal.com/browse/track/209499616",
      "tiktok": null,
      "yandex": "https://music.yandex.com/album/19854446/track/96764343",
      "youtube": "https://youtu.be/gqnAPRtTnSs"
    },
    genre: "Deep House",
    id: "passages",
    image: "/images/releases/2021/passages.jpg",
    label: null,
    title: "Passages",
    type: "Releases",
    video: "gqnAPRtTnSs",
    year: 2021
  },
  {
    album: "Passages",
    artists: "Bayza",
    cover: "passages",
    dark: false,
    date: "2021-12-30 00:00:05",
    description: "This is the instrumental version of \"<a class=\"text-white\" href=\"https://bayzamusic.com/releases/2021/thumbs\" target=\"_blank\" title=\"Sabrina Carpenter - Thumbs (Bayza Bootleg)\">Sabrina Carpenter - Thumbs (Bayza Bootleg)</a>\"",
    duration: "3:23",
    fanlink: "lnk.bayzamusic.com/thumbs",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B09N68K4GX",
      "amazon-music": "https://music.amazon.com/albums/B09N6DDN5X?trackAsin=B09N68K4GX",
      "apple": "https://music.apple.com/us/album/passages/1600730723?i=1600730727?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/thumbs/16170766",
      "deezer": "https://www.deezer.com/en/track/1593460571",
      "download": null,
      "itunes": "https://music.apple.com/us/album/passages/1600730723?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/thumbs",
      "spotify": "https://open.spotify.com/track/3C0Z376nrmzPNvDxRQSOrR?si",
      "tidal": "https://tidal.com/browse/track/209499617",
      "tiktok": null,
      "yandex": "https://music.yandex.com/album/19854446/track/96764344",
      "youtube": "https://youtu.be/9u_UwD-WpSE"
    },
    genre: "Deep House",
    id: "thumbs",
    image: "/images/releases/2021/passages.jpg",
    label: null,
    title: "Thumbs - Instrumental",
    type: "Releases",
    video: "9u_UwD-WpSE",
    year: 2021
  },
  {
    album: "Passages",
    artists: "Bayza",
    cover: "passages",
    dark: false,
    date: "2021-12-30 00:00:04",
    description: "This is the instrumental version of \"<a class=\"text-white\" href=\"https://bayzamusic.com/releases/2021-bootlegs/lo-vas-a-olvidar\" target=\"_blank\" title=\"Billie Eilish, ROSALÍA - Lo Vas A Olvidar (Bayza Bootleg)\">Billie Eilish, ROSALÍA - Lo Vas A Olvidar (Bayza Bootleg)</a>\"",
    duration: "3:18",
    fanlink: "lnk.bayzamusic.com/LoVasAOlvidar",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B09N61Z6JW",
      "amazon-music": "https://music.amazon.com/albums/B09N6DDN5X?trackAsin=B09N61Z6JW",
      "apple": "https://music.apple.com/us/album/passages/1600730723?i=1600730728?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/lo-vas-a-olvidar/16170768",
      "deezer": "https://www.deezer.com/en/track/1593460581",
      "download": null,
      "itunes": "https://music.apple.com/us/album/passages/1600730723?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/lo-vas-a-olvidar",
      "spotify": "https://open.spotify.com/track/24oDwzecr6P1M99J75MP3I?si",
      "tidal": "https://tidal.com/browse/track/209499618",
      "tiktok": null,
      "yandex": "https://music.yandex.com/album/19854446/track/96764345",
      "youtube": "https://youtu.be/9u_UwD-WpSE"
    },
    genre: "Deep House",
    id: "lovasaolvidar",
    image: "/images/releases/2021/passages.jpg",
    label: null,
    title: "Lo Vas A Olvidar - Instrumental",
    type: "Releases",
    video: "VXXsLZm3HVc",
    year: 2021
  },
  {
    album: "Passages",
    artists: "Bayza",
    cover: "passages",
    dark: false,
    date: "2021-12-30 00:00:03",
    description: "This is the instrumental version of \"<a class=\"text-white\" href=\"https://bayzamusic.com/releases/2021-bootlegs/my-head-my-heart\" target=\"_blank\" title=\"Ava Max - My Head & My Heart (Bayza Bootleg)\">Ava Max - My Head & My Heart (Bayza Bootleg)</a>\"",
    duration: "3:31",
    fanlink: "lnk.bayzamusic.com/MyHeadMyHeart",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B09N681P5P",
      "amazon-music": "https://music.amazon.com/albums/B09N6DDN5X?trackAsin=B09N681P5P",
      "apple": "https://music.apple.com/us/album/passages/1600730723?i=1600730729?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/my-head-my-heart/16170771",
      "deezer": "https://www.deezer.com/en/track/1593460591",
      "download": null,
      "itunes": "https://music.apple.com/us/album/passages/1600730723?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/my-head-my-heart",
      "spotify": "https://open.spotify.com/track/4EUzTSJRJ82Xj6O4MSMRCe?si",
      "tidal": "https://tidal.com/browse/track/209499619",
      "tiktok": null,
      "yandex": "https://music.yandex.com/album/19854446/track/96764346",
      "youtube": "https://youtu.be/JaN96BTWzZo"
    },
    genre: "Deep House",
    id: "myheadmyheart",
    image: "/images/releases/2021/passages.jpg",
    label: null,
    title: "My Head & My Heart - Instrumental",
    type: "Releases",
    video: "JaN96BTWzZo",
    year: 2021
  },
  {
    album: "Passages",
    artists: "Bayza",
    cover: "passages",
    dark: false,
    date: "2021-12-30 00:00:02",
    description: "This is the instrumental version of \"<a class=\"text-white\" href=\"https://bayzamusic.com/releases/2020-bootlegs/not-my-baby\" target=\"_blank\" title=\"INNA - Not My Baby (Bayza Bootleg)\">INNA - Not My Baby (Bayza Bootleg)</a>\"",
    duration: "3:19",
    fanlink: "lnk.bayzamusic.com/NotMyBaby",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B09N6K71BB",
      "amazon-music": "https://music.amazon.com/albums/B09N6DDN5X?trackAsin=B09N6K71BB",
      "apple": "https://music.apple.com/us/album/passages/1600730723?i=1600730731?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/not-my-baby/16170773",
      "deezer": "https://www.deezer.com/en/track/1593460601",
      "download": null,
      "itunes": "https://music.apple.com/us/album/passages/1600730723?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/not-my-baby",
      "spotify": "https://open.spotify.com/track/4cMA8RjP9QHy2gzBY0vefh?si",
      "tidal": "https://tidal.com/browse/track/209499620",
      "tiktok": null,
      "yandex": "https://music.yandex.com/album/19854446/track/96764347",
      "youtube": "https://youtu.be/KIP1Wa8lEsk"
    },
    genre: "Deep House",
    id: "notmybaby",
    image: "/images/releases/2021/passages.jpg",
    label: null,
    title: "Not My Baby - Instrumental",
    type: "Releases",
    video: "KIP1Wa8lEsk",
    year: 2021
  },
  {
    album: "Passages",
    artists: "Bayza",
    cover: "passages",
    dark: false,
    date: "2021-12-30 00:00:01",
    description: "This is the instrumental version of \"<a class=\"text-white\" href=\"https://bayzamusic.com/releases/2020-bootlegs/desert-rose-enta-omri\" target=\"_blank\" title=\"Noel Kharman - Desert Rose / انت عمري Mashup (Bayza Remix)\">Noel Kharman - Desert Rose / انت عمري Mashup (Bayza Remix)</a>\"",
    duration: "3:49",
    fanlink: "lnk.bayzamusic.com/DesertRose",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B09N639BK2",
      "amazon-music": "https://music.amazon.com/albums/B09N6DDN5X?trackAsin=B09N639BK2",
      "apple": "https://music.apple.com/us/album/passages/1600730723?i=1600730732?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/desert-rose/16170774",
      "deezer": "https://www.deezer.com/en/track/1593460611",
      "download": null,
      "itunes": "https://music.apple.com/us/album/passages/1600730723?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/desert-rose",
      "spotify": "https://open.spotify.com/track/6ZFoAt8MbI2p9rTyCwnPpM?si",
      "tidal": "https://tidal.com/browse/track/209499621",
      "tiktok": null,
      "yandex": "https://music.yandex.com/album/19854446/track/96764348",
      "youtube": "https://youtu.be/h1aLkuT0ctI"
    },
    genre: "Deep House",
    id: "desert-rose",
    image: "/images/releases/2021/passages.jpg",
    label: null,
    title: "Desert Rose - Instrumental",
    type: "Releases",
    video: "h1aLkuT0ctI",
    year: 2021
  },
  {
    artists: "DJ Phellix, Bayza, Sheenubb ft. Sant",
    cover: "pirhan",
    dark: true,
    date: "2021-12-15 00:00:00",
    description: null,
    duration: "4:55",
    fanlink: "lnk.bayzamusic.com/Pirhan",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B09N9DDY9C",
      "amazon-music": "https://music.amazon.com/albums/B09N9DDY9C",
      "apple": "https://music.apple.com/us/album/1599229315?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/pirhan/16031083",
      "deezer": "https://www.deezer.com/en/album/279308962",
      "download": null,
      "itunes": "https://music.apple.com/us/album/1599229315?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/ariorecords/dj-phellix-bayza-sheenubb-ft-sant-pirhan-original-mix",
      "spotify": "https://open.spotify.com/track/4K3Xlz1PMFo3r7nXNoS780?si",
      "tidal": "https://tidal.com/browse/album/208200247",
      "tiktok": "https://vm.tiktok.com/ZM8cdkf1a",
      "yandex": null,
      "youtube": "https://youtu.be/_HNN88li9kI"
    },
    genre: "Organic House / Deep House",
    id: "pirhan",
    image: "/images/releases/2021/pirhan.jpg",
    label: "Ario Records",
    title: "Pirhan",
    type: "Releases",
    video: "_HNN88li9kI",
    year: 2021
  },
  {
    artists: "Sabrina Carpenter",
    cover: "thumbs",
    dark: false,
    date: "2021-12-02 00:00:00",
    description: "Hi guys, I hope you like this track, someone asked me to remix Thumbs by Sabrina Carpenter, I liked the original song when I first listened to it so I decided to finish this remix. I've also uploaded an <a class=\"text-white\" href=\"https://www.youtube.com/watch?v=9u_UwD-WpSE\" target=\"_blank\" title=\"Bayza - Thumbs | Instrumental Version\">Instrumental Version</a></b> for those who want to listen without the vocals.",
    duration: "3:23",
    fanlink: "lnk.bayzamusic.com/ThumbsRemix",
    fanlinks: {
      "amazon": null,
      "amazon-music": null,
      "apple": null,
      "bandcamp": "https://bayza.bandcamp.com/track/thumbs-bayza-remix",
      "beatport": null,
      "deezer": null,
      "download": "https://www.toneden.io/bayza/post/thumbs-bayza-remix",
      "itunes": null,
      "soundcloud": "https://soundcloud.com/bayza/thumbs-bayza-remix",
      "spotify": null,
      "tidal": null,
      "tiktok": null,
      "yandex": null,
      "youtube": "https://youtu.be/SPlamGgkl00"
    },
    genre: "Dance",
    id: "thumbs-remix",
    image: "/images/releases/2021/thumbs.jpg",
    label: null,
    link: "-bootlegs",
    title: "Thumbs (Bayza Remix)",
    type: "Bootlegs/Remixes",
    video: "SPlamGgkl00",
    year: 2021
  },
  {
    artists: "Bayza",
    cover: "take-me-home",
    dark: false,
    date: "2021-06-25 00:00:00",
    description: "Bayza brings \"Take Me Home\" under the German label \"The Night Drive\". The inspiration for this track was to try to transmit nighty vibes that are suited perfectly for car driving or club parties because of its modern house music style.",
    duration: "2:58",
    fanlink: "lnk.bayzamusic.com/TakeMeHome",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B095SZW2GV",
      "amazon-music": "https://music.amazon.com/albums/B095SZW2GV",
      "anghami": "https://play.anghami.com/song/111077051",
      "apple": "https://music.apple.com/us/album/1569349725?app=music&ls=1",
      "bandcamp": null,
      "beatport": "https://www.beatport.com/track/take-me-home/15341109",
      "deezer": "https://www.deezer.com/en/album/232620752",
      "download": null,
      "itunes": "https://music.apple.com/us/album/1569349725?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/take-me-home",
      "spotify": "https://open.spotify.com/track/1uD20gyamF7x91Nn6IUlME?si",
      "tidal": "https://tidal.com/browse/album/185398916",
      "tiktok": "https://vm.tiktok.com/ZMdfURKan",
      "yandex": "https://music.yandex.com/album/15798165",
      "youtube": "https://youtu.be/BwKO7sfFVAA"
    },
    genre: "Deep House",
    id: "take-me-home",
    image: "/images/releases/2021/take-me-home.jpg",
    label: "The Night Drive",
    title: "Take Me Home",
    type: "Releases",
    video: "BwKO7sfFVAA",
    year: 2021
  },
  {
    artists: "DeejaVu X Bayza",
    cover: "feels",
    dark: false,
    date: "2021-04-23 00:00:00",
    description: "Fresh chill house track in collaboration with Finnish producer \"DeejaVu\".",
    duration: "2:46",
    fanlink: "lnk.bayzamusic.com/Feels",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B0923VPXQW",
      "amazon-music": "https://music.amazon.com/albums/B0923VPXQW",
      "apple": "https://music.apple.com/us/album/feels-single/1562506442?app=music&ls=1",
      "bandcamp": "https://bayza.bandcamp.com/track/feels",
      "beatport": null,
      "deezer": "https://www.deezer.com/us/track/1334598062",
      "download": "https://www.toneden.io/bayza/post/feels",
      "itunes": "https://music.apple.com/us/album/feels-single/1562506442?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/feels",
      "spotify": "https://open.spotify.com/track/16A0kDr2Z76OfTz2Ffyrri?si",
      "tidal": "https://tidal.com/browse/album/180056067",
      "tiktok": "https://vm.tiktok.com/ZMexphPbu",
      "yandex": "https://music.yandex.com/album/14788954",
      "youtube": "https://youtu.be/hWhQJKLyyss"
    },
    genre: "Deep House / Chill House",
    id: "feels",
    image: "/images/releases/2021/feels.jpg",
    label: null,
    title: "Feels",
    type: "Releases",
    video: "hWhQJKLyyss",
    year: 2021
  },
  {
    artists: "Bayza",
    cover: "feel-so-lonely",
    dark: true,
    date: "2021-04-16 00:00:00",
    description: "Fresh dance/house tune \"Feel So Lonely\" is OUT!",
    duration: "2:48",
    fanlink: "lnk.bayzamusic.com/FeelSoLonely",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B091G2BYZS",
      "amazon-music": "https://music.amazon.com/albums/B091G2BYZS",
      "apple": "https://music.apple.com/us/album/feel-so-lonely-single/1561135882?app=music&ls=1",
      "bandcamp": null,
      "beatport": null,
      "deezer": "https://www.deezer.com/en/album/217630312",
      "download": null,
      "itunes": "https://music.apple.com/us/album/feel-so-lonely-single/1561135882?app=itunes&ls=1",
      "soundcloud": null,
      "spotify": "https://open.spotify.com/track/18ir1AdSzs8K1OOb4XQacu?si",
      "tidal": "https://tidal.com/browse/album/179545879",
      "tiktok": "https://vm.tiktok.com/ZMeHNh8sb",
      "yandex": "https://music.yandex.com/album/14636288",
      "youtube": "https://youtu.be/q-UK_m9rq3Q"
    },
    genre: "Slap House / Deep House",
    id: "feel-so-lonely",
    image: "/images/releases/2021/feel-so-lonely.jpg",
    label: "FRQNCY",
    title: "Feel So Lonely",
    type: "Releases",
    video: "q-UK_m9rq3Q",
    year: 2021
  },
  {
    artists: "Bayza feat. Giulia Mihai",
    cover: "you-said-goodbye",
    dark: false,
    date: "2021-03-31 00:00:02",
    description: "This time I worked with a Romanian singer named \"Giulia Mihai\". She wrote the lyrics and provided her voice for this song. The song is kinda sad/melancholic with lyrics in English and Spanish language.",
    duration: "3:19",
    fanlink: "lnk.bayzamusic.com/YouSaidGoodbye",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B08YFL84C3/",
      "amazon-music": "https://music.amazon.com/albums/B08YFL84C3",
      "apple": "https://music.apple.com/us/album/you-said-goodbye-feat-giulia-mihai-single/1557511564?app=music&ls=1",
      "bandcamp": "https://bayza.bandcamp.com/track/you-said-goodbye",
      "beatport": "https://www.beatport.com/track/you-said-goodbye-feat-giulia-mihai/15023484",
      "deezer": "https://www.deezer.com/en/album/213461082",
      "download": "https://www.toneden.io/bayza/post/you-said-goodbye",
      "itunes": "https://music.apple.com/us/album/you-said-goodbye-feat-giulia-mihai-single/1557511564?app=itunes&ls=1",
      "napster": "https://www.napster.com/artist/bayza/album/you-said-goodbye",
      "soundcloud": "https://soundcloud.com/miss-deepshine/bayza-feat-giulia-mihai-you-said-goodbye",
      "spotify": "https://open.spotify.com/track/1GpCKLM9yTtgufa5l7dpqQ?si",
      "tidal": "https://tidal.com/browse/album/176441860",
      "tiktok": "https://vm.tiktok.com/ZMey7V76P/",
      "yandex": "https://music.yandex.com/album/14306777",
      "youtube": "https://youtu.be/5Pt9qzAqVxA"
    },
    genre: "Deep House",
    id: "you-said-goodbye",
    image: "/images/releases/2021/you-said-goodbye.jpg",
    label: "DeepShine Records",
    title: "You Said Goodbye",
    type: "Releases",
    video: "5Pt9qzAqVxA",
    year: 2021
  },
  {
    artists: "Otilia",
    cover: "otilia-remix",
    dark: false,
    date: "2021-03-31 00:00:01",
    description: null,
    duration: "3:02",
    fanlink: "lnk.bayzamusic.com/Diamante",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B08ZMM4PTN",
      "amazon-music": "https://music.amazon.com/albums/B08ZMLXDV4?trackAsin=B08ZMM4PTN",
      "apple": "https://music.apple.com/pa/album/diamante-bayza-remix/1559053659?i=1559055577?app=music&ls=1",
      "bandcamp": "https://bayza.bandcamp.com/track/diamante-bayza-remix",
      "beatport": "https://www.beatport.com/track/diamante/15075125",
      "deezer": "https://www.deezer.com/us/track/1279371512",
      "download": "https://www.toneden.io/bayza/post/diamante-bayza-remix",
      "itunes": "https://music.apple.com/pa/album/diamante-bayza-remix/1559053659?i=1559055577?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/diamante-remix",
      "spotify": "https://open.spotify.com/track/2Ng9yyLp3xH55tsSFNmb36?si",
      "tidal": "https://tidal.com/browse/track/177616393",
      "tiktok": "https://vm.tiktok.com/ZMef9mkYr",
      "yandex": "https://music.yandex.com/album/14463629/track/79531770",
      "youtube": "https://youtu.be/xjR_d8Aw8QY"
    },
    genre: "Deep House",
    id: "diamante",
    image: "/images/releases/2021/otilia-remix.jpg",
    label: "JHaps Records",
    title: "Diamante (Bayza Remix)",
    type: "Releases",
    video: "xjR_d8Aw8QY",
    year: 2021
  },
  {
    artists: "Otilia",
    cover: "otilia-remix",
    dark: false,
    date: "2021-03-31 00:00:00",
    description: null,
    duration: "2:43",
    fanlink: "lnk.bayzamusic.com/IDontKnow",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B08ZMLG3TW",
      "amazon-music": "https://music.amazon.com/albums/B08ZMLXDV4?trackAsin=B08ZMLG3TW",
      "apple": "https://music.apple.com/us/album/i-dont-know-bayza-remix/1559053659?i=1559055822?app=music&ls=1",
      "bandcamp": "https://bayza.bandcamp.com/track/i-dont-know-bayza-remix",
      "beatport": "https://www.beatport.com/track/i-dont-know/15075129",
      "deezer": "https://www.deezer.com/us/track/1279371542",
      "download": "https://www.toneden.io/bayza/post/otilia-i-don-t-know-bayza-remix",
      "itunes": "https://music.apple.com/us/album/i-dont-know-bayza-remix/1559053659?i=1559055822?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/i-dont-know-bayza-remix",
      "spotify": "https://open.spotify.com/track/6CSQOjC9AjCiaAUTYmCwrP?si",
      "tidal": "https://tidal.com/browse/track/177616395",
      "tiktok": "https://vm.tiktok.com/ZMefdCFar",
      "yandex": "https://music.yandex.com/album/14463629/track/79531772",
      "youtube": "https://youtu.be/gfxe7vJYbKo"
    },
    genre: "Deep House",
    id: "i-dont-know",
    image: "/images/releases/2021/otilia-remix.jpg",
    label: "JHaps Records",
    title: "I Don't Know (Bayza Remix)",
    type: "Releases",
    video: "gfxe7vJYbKo",
    year: 2021
  },
  {
    artists: "Bayza",
    cover: "without-you",
    dark: false,
    date: "2021-03-08 00:00:00",
    description: "Releasing some chill deep house with DeepShine Records!",
    duration: "2:47",
    fanlink: "lnk.bayzamusic.com/without-you",
    fanlinkId: "without-you",
    fanlinks: {
      "amazon": "https://www.amazon.com/Without-You-Bayza/dp/B08WWQ76R7",
      "amazon-music": "https://music.amazon.com/albums/B08WWQ76R7",
      "apple": "https://music.apple.com/us/album/without-you-single/1554291555?app=music&ls=1",
      "bandcamp": "https://bayza.bandcamp.com/track/without-you",
      "beatport": "https://www.beatport.com/track/without-you/14942522",
      "deezer": "https://www.deezer.com/en/album/208688602",
      "download": "https://www.toneden.io/bayza/post/without-you",
      "itunes": "https://music.apple.com/us/album/without-you-single/1554291555?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/miss-deepshine/bayza-without-you",
      "spotify": "https://open.spotify.com/track/6VO7FOoYQ2tjjdecVPlOli?si",
      "tidal": "https://tidal.com/browse/album/174130575",
      "tiktok": "https://vm.tiktok.com/ZMermEXNJ",
      "yandex": "https://music.yandex.com/album/13955690",
      "youtube": "https://youtu.be/Ncxok5G7yOA"
    },
    genre: "Deep House",
    id: "without-you",
    image: "/images/releases/2021/without-you.jpg",
    label: null,
    title: "Without You",
    type: "Releases",
    video: "Ncxok5G7yOA",
    year: 2021
  },
  {
    artists: "Ava Max",
    cover: "my-head-my-heart",
    dark: false,
    date: "2021-02-16 00:00:00",
    description: "Ava Max - My Head & My Heart (Bayza Remix)",
    duration: "3:33",
    fanlink: "lnk.bayzamusic.com/my-head-my-heart",
    fanlinkId: "my-head-my-heart",
    fanlinks: {
      bandcamp: "https://bayza.bandcamp.com/track/my-head-my-heart-bayza-remix",
      download: "https://www.toneden.io/bayza/post/ava-max-my-head-my-heart-bayza-remix",
      soundcloud: "https://soundcloud.com/bayza-bootlegs/my-head-my-heart-bayza-remix",
      youtube: "https://youtu.be/eKGxQxm9FUA"
    },
    genre: "Deep House",
    id: "my-head-my-heart",
    image: "/images/releases/2021/my-head-my-heart.jpg",
    label: null,
    link: "-bootlegs",
    title: "My Head & My Heart (Bayza Remix)",
    type: "Bootlegs/Remixes",
    video: "eKGxQxm9FUA",
    year: 2021
  },
  {
    artists: "Bayza",
    cover: "looking-at-you",
    dark: false,
    date: "2021-02-12 00:00:00",
    description: "Starting 2021 with some deep and slappy stuff!",
    duration: "3:18",
    fanlink: "lnk.bayzamusic.com/LookingAtYou",
    fanlinks: {
      "amazon": "https://www.amazon.com/Looking-At-You-Bayza/dp/B08VS82LX5",
      "amazon-music": "https://music.amazon.com/albums/B08VS82LX5",
      "apple": "https://music.apple.com/us/album/looking-at-you-single/1552093678?app=music&ls=1",
      "bandcamp": "https://bayza.bandcamp.com/track/looking-at-you",
      "beatport": null,
      "deezer": "https://www.deezer.com/en/album/204865582",
      "download": "https://www.toneden.io/bayza/post/looking-at-you",
      "itunes": "https://music.apple.com/us/album/looking-at-you-single/1552093678?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/looking-at-you",
      "spotify": "https://open.spotify.com/album/1FeIeewafur1nUMlWQvH5I?si",
      "tidal": "https://tidal.com/browse/album/172262273",
      "tiktok": "https://vm.tiktok.com/ZMeRwyCeb",
      "yandex": "https://music.yandex.com/album/13746009",
      "youtube": "https://youtu.be/Yd5LZuOyCpg"
    },
    genre: "Deep House / Slap House",
    id: "looking-at-you",
    image: "/images/releases/2021/looking-at-you.jpg",
    label: null,
    title: "Looking At You",
    type: "Releases",
    video: "Yd5LZuOyCpg",
    year: 2021
  },
  {
    artists: "Billie Eilish, ROSALÍA",
    cover: "lo-vas-a-olvidar",
    dark: false,
    date: "2021-01-22 00:00:00",
    description: "I loved Billie Eilish and ROSALÍA collaboration. I was amazed to hear Billie singing in my language (spanish). Since first time listening to it I felt that I had to remix it with my deep vibe.",
    duration: "3:28",
    fanlink: "lnk.bayzamusic.com/LVAO",
    fanlinkId: "LVAO",
    fanlinks: {
      bandcamp: "https://bayza.bandcamp.com/track/lo-vas-a-olvidar-bayza-remix",
      download: "https://www.toneden.io/bayza/post/billie-eilish-rosal-a-lo-vas-a-olvidar-bayza-remix",
      soundcloud: "https://soundcloud.com/bayza-bootlegs/lo-vas-a-olvidar-bayza-remix",
      youtube: "https://youtu.be/RilJRFTno6M"
    },
    genre: "Deep House",
    id: "lo-vas-a-olvidar",
    image: "/images/releases/2021/lo-vas-a-olvidar.jpg",
    label: null,
    link: "-bootlegs",
    title: "Lo Vas A Olvidar (Bayza Remix)",
    type: "Bootlegs/Remixes",
    video: "RilJRFTno6M",
    year: 2021
  },
  {
    artists: "Bayza",
    cover: "lamentos",
    dark: false,
    date: "2020-10-31 00:00:00",
    description: "I had the idea to create a dark, mysterious, and somewhat scary Halloween-themed track for October 31. And here it is, hope you like it!",
    duration: "3:36",
    fanlink: "lnk.bayzamusic.com/lamentos",
    fanlinks: {
      "amazon": "https://www.amazon.com/Lamentos-Bayza/dp/B08KYCCYGM",
      "amazon-music": "https://music.amazon.com/albums/B08KYCCYGM",
      "apple": "https://music.apple.com/album/lamentos-single/1535188133?app=music&ls=1",
      "bandcamp": "https://bayza.bandcamp.com/track/lamentos",
      "beatport": "https://www.beatport.com/track/lamentos/15125257",
      "deezer": "https://www.deezer.com/en/album/178573382",
      "download": "https://www.toneden.io/bayza/post/lamentos",
      "itunes": "https://music.apple.com/album/lamentos-single/1535188133?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/lamentos",
      "spotify": "https://open.spotify.com/album/3skBUyFSoDnMA69OCbdLin?si",
      "tidal": "https://tidal.com/browse/album/158113633",
      "tiktok": "https://vm.tiktok.com/ZSCnUvDA",
      "yandex": "https://music.yandex.com/album/12395537",
      "youtube": "https://youtu.be/nQ0A1WWxuFY"
    },
    genre: "Deep House",
    id: "lamentos",
    image: "/images/releases/2020/lamentos.jpg",
    label: null,
    title: "Lamentos",
    type: "Releases",
    video: "nQ0A1WWxuFY",
    year: 2020
  },
  {
    artists: "Bayza & Dimatis",
    cover: "reborn",
    dark: false,
    date: "2020-10-22 00:00:00",
    description: "We made this track for a gaming community here in Panama. It's like a Trap style, hope you enjoy!.",
    duration: "2:42",
    fanlink: "lnk.bayzamusic.com/reborn",
    fanlinks: {
      "amazon": "https://www.amazon.com/No-Guarantee-Bayza/dp/B08KY8ZJV7",
      "amazon-music": "https://music.amazon.com/albums/B08KY8ZJV7",
      "apple": "https://music.apple.com/album/reborn-single/1535187248?app=music&ls=1",
      "bandcamp": "https://bayza.bandcamp.com/track/reborn",
      "beatport": null,
      "deezer": "https://www.deezer.com/en/album/178782202",
      "download": "https://www.toneden.io/bayza/post/reborn",
      "itunes": "https://music.apple.com/album/reborn-single/1535187248?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/reborn",
      "spotify": "https://open.spotify.com/track/3POCFD2UIKRvmySfhQvRgU?si",
      "tidal": "https://tidal.com/browse/album/158112844",
      "tiktok": "https://vm.tiktok.com/ZSQNYnMg",
      "youtube": "https://youtu.be/Uqm00tl0nKQ"
    },
    genre: "Trap",
    id: "reborn",
    image: "/images/releases/2020/reborn.jpg",
    label: null,
    title: "Reborn",
    type: "Releases",
    video: "Uqm00tl0nKQ",
    year: 2020
  },
  {
    artists: "Bayza",
    cover: "no-guarantee",
    dark: false,
    date: "2020-10-19 00:00:00",
    description: "There is just no guarantee, for you and me...",
    duration: "3:38",
    fanlink: "lnk.bayzamusic.com/no-guarantee",
    fanlinkId: "no-guarantee",
    fanlinks: {
      "amazon": "https://www.amazon.com/No-Guarantee-Bayza/dp/B08KGYK2C7",
      "amazon-music": "https://music.amazon.com/albums/B08KGYK2C7",
      "apple": "https://music.apple.com/album/no-guarantee-single/1533985778?app=music&ls=1",
      "bandcamp": "https://bayza.bandcamp.com/track/no-guarantee",
      "beatport": "https://www.beatport.com/release/no-guarantee/3143902",
      "deezer": "https://www.deezer.com/en/album/176788332",
      "download": "",
      "itunes": "https://music.apple.com/album/no-guarantee-single/1533985778?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/miss-deepshine/bayza-no-guarantee",
      "spotify": "https://open.spotify.com/album/0Q5SIAHGCmJqTOcMCpeh96?si",
      "tidal": "https://tidal.com/browse/album/156986955",
      "tiktok": "https://vm.tiktok.com/ZSxQbH7v",
      "yandex": "https://music.yandex.com/album/12300457",
      "youtube": "https://youtu.be/YPLPc6xGWK4"
    },
    genre: "Deep House",
    id: "no-guarantee",
    image: "/images/releases/2020/no-guarantee.jpg",
    label: "DeepShine Records",
    title: "No Guarantee",
    type: "Releases",
    video: "YPLPc6xGWK4",
    year: 2020
  },
  {
    artists: "Dimatis & Bayza",
    cover: "hold-on-to-me",
    dark: false,
    date: "2020-09-25 00:00:00",
    description: "This track is different from my usual style because it is a collaboration with my twin brother Dimatis, he is a Melodic Dubstep producer. We don't collaborate so often, but when we do, we create styles that are different from both of us. This time we try some Future Bass with vocals. Hope you like it!",
    duration: "3:27",
    fanlink: "lnk.bayzamusic.com/hold-on-to-me",
    fanlinkId: "hold-on-to-me",
    fanlinks: {
      "amazon": "https://www.amazon.com/Hold-Me-Dimatis-Bayza/dp/B08FFMF4L3",
      "amazon-music": "https://music.amazon.com/albums/B08FFMF4L3",
      "apple": "https://music.apple.com/us/album/hold-on-to-me-single/1526294383?app=music&ls=1",
      "deezer": "https://www.deezer.com/en/album/165690312",
      "download": "https://www.toneden.io/bayza/post/dimatis-bayza-hold-on-to-me",
      "itunes": "https://music.apple.com/us/album/hold-on-to-me-single/1526294383?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/hold-on-to-me",
      "spotify": "https://open.spotify.com/track/0U9BPZn0nvkUYFfuPteBmE?si",
      "tidal": "http://tidal.com/browse/album/151393778",
      "tiktok": "https://vm.tiktok.com/ZSmq7e54",
      "youtube": "https://youtu.be/N2sZKeX_xGI"
    },
    genre: "Future Bass",
    id: "hold-on-to-me",
    image: "/images/releases/2020/hold-on-to-me.jpg",
    label: null,
    title: "Hold On To Me",
    type: "Releases",
    video: "N2sZKeX_xGI",
    year: 2020
  },
  {
    artists: "Melanie Martinez",
    cover: "fire-drill",
    dark: false,
    date: "2020-09-18 00:00:00",
    description: "There was some people of Melanie Martinez's community that came to my 'Strawberry Shortcake' Remix and they gave positive comments and wanted me to make more of Melanie. I present this time a remix for 'Fire Drill' Hope you like it.",
    duration: "4:25",
    fanlink: "lnk.bayzamusic.com/FireDrill",
    fanlinks: {
      soundcloud: "https://soundcloud.com/bayza-bootlegs/fire-drill-bayza-bootleg",
      youtube: "https://youtu.be/kYNUcObW_H0"
    },
    genre: "Deep House",
    id: "fire-drill",
    image: "/images/releases/2020/fire-drill.jpg",
    label: null,
    link: "-bootlegs",
    title: "Fire Drill (Bayza Bootleg)",
    type: "Bootlegs/Remixes",
    video: "kYNUcObW_H0",
    year: 2020
  },
  {
    artists: "Bayza",
    cover: "solace",
    dark: false,
    date: "2020-08-28 00:00:00",
    description: "Bayza is back on PalmTherapySounds with his track \"Solace\".",
    duration: "3:52",
    fanlink: "lnk.bayzamusic.com/solace",
    fanlinks: {
      "amazon": "https://www.amazon.com/Solace-Bayza/dp/B08FXRGBTY",
      "amazon-music": "https://music.amazon.com/albums/B08FXRGBTY",
      "anghami": "https://play.anghami.com/song/83466093",
      "apple": "https://music.apple.com/album/solace-single/1527771223?app=music&ls=1",
      "bandcamp": "https://bayza.bandcamp.com/track/solace",
      "deezer": "https://www.deezer.com/en/album/167194272",
      "download": null,
      "itunes": "https://music.apple.com/album/solace-single/1527771223?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/palmtherapysounds/bayza-solace",
      "spotify": "https://open.spotify.com/album/22i8HksJAROoLVOqKzzsMX?si",
      "tidal": "https://tidal.com/browse/album/152057763",
      "tiktok": "https://vm.tiktok.com/ZSuDrpku",
      "yandex": "https://music.yandex.com/album/11793661",
      "youtube": "https://youtu.be/oYqe05-Aha0"
    },
    genre: "Deep House",
    id: "solace",
    image: "/images/releases/2020/solace.jpg",
    label: "PalmTherapySounds",
    title: "Solace",
    type: "Releases",
    video: "oYqe05-Aha0",
    year: 2020
  },
  {
    artists: "Eress",
    cover: "make-believe-remix",
    dark: false,
    date: "2020-08-01 00:00:00",
    description: "I was participating in a remix competition for \"Eress - Make Believe\" and I won the first place. :)",
    duration: "4:28",
    fanlink: "lnk.bayzamusic.com/make-believe",
    fanlinkId: "make-believe",
    fanlinks: {
      "amazon": "https://www.amazon.com/dp/B08D5X9L9P/",
      "amazon-music": "https://music.amazon.com/albums/B08D6J76TQ?trackAsin=B08D5X9L9P",
      "apple": "https://music.apple.com/us/album/1523752558?i=1523752560?app=music&ls=1",
      "deezer": "https://www.deezer.com/en/track/1022970892",
      "itunes": "https://music.apple.com/us/album/1523752558?i=1523752560?app=itunes&ls=1",
      "spotify": "https://open.spotify.com/track/5aNJ27YbvoNsy4kT8txSlB?si",
      "tiktok": "https://vm.tiktok.com/ZMJMVFvQA",
      "youtube": "https://youtu.be/MjaLp6MNm4g"
    },
    genre: "Deep House",
    id: "make-believe",
    image: "/images/releases/2020/make-believe-remix.jpg",
    label: null,
    title: "Make Believe (Bayza Remix)",
    type: "Releases",
    video: "MjaLp6MNm4g",
    year: 2020
  },
  {
    artists: "Bayza",
    cover: "miracle",
    dark: false,
    date: "2020-07-10 00:00:00",
    description: "A Miracle is an effect or extraordinary event not explicable by natural, scientific law. It also characterizes any beneficial event that is statistically improbable, and some coincidences can bee seen as miracles.",
    duration: "3:12",
    fanlink: "lnk.bayzamusic.com/miracle",
    fanlinks: {
      "amazon": "https://www.amazon.com/Miracle-Bayza/dp/B08B1VJ9YK",
      "amazon-music": "https://music.amazon.com/albums/B08B1VJ9YK",
      "apple": "https://music.apple.com/us/album/miracle-single/1517837338?app=music&ls=1",
      "bandcamp": "https://bayza.bandcamp.com/track/miracle",
      "beatport": "https://www.beatport.com/track/miracle/14974894",
      "deezer": "https://www.deezer.com/en/album/154007702",
      "download": "https://www.toneden.io/bayza/post/miracle",
      "itunes": "https://music.apple.com/us/album/miracle-single/1517837338?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/miracle",
      "spotify": "https://open.spotify.com/album/2Fejxzi2GxOeoCvaF7e3j6?si",
      "tidal": "https://tidal.com/browse/album/144714352",
      "tiktok": "https://vm.tiktok.com/JLej2G3",
      "yandex": "https://music.yandex.com/album/11036717",
      "youtube": "https://youtu.be/-vx3oZ4j4h0"
    },
    genre: "Deep House",
    id: "miracle",
    image: "/images/releases/2020/miracle.jpg",
    label: null,
    title: "Miracle",
    type: "Releases",
    video: "-vx3oZ4j4h0",
    year: 2020
  },
  {
    artists: "DJ SK & Bayza",
    cover: "alone",
    dark: false,
    date: "2020-06-24 00:00:00",
    description: "My fourth release under DeepShine Records. This time in collaboration with Moroccan producer DJ SK.",
    duration: "4:24",
    fanlink: "lnk.bayzamusic.com/alone",
    fanlinks: {
      "amazon": "https://www.amazon.com/Alone-DJ-SK-MA-Bayza/dp/B089597J6Q",
      "amazon-music": "https://music.amazon.com/albums/B089597J6Q",
      "apple": "https://music.apple.com/us/album/alone-single/1515190787?app=music&ls=1",
      "beatport": "https://www.beatport.com/release/alone/2981881",
      "deezer": "https://www.deezer.com/en/album/150568762",
      "download": null,
      "itunes": "https://music.apple.com/us/album/alone-single/1515190787?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/miss-deepshine/dj-sk-bayza-alone-original-mix",
      "spotify": "https://open.spotify.com/album/1bpVJxbwqSu9vJ2drvTdpg?si",
      "tidal": "https://tidal.com/browse/album/142790472",
      "tiktok": "https://vm.tiktok.com/J8XyVFk",
      "youtube": "https://youtu.be/FKTMZBDzgD8"
    },
    genre: "Deep House",
    id: "alone",
    image: "/images/releases/2020/alone.jpg",
    label: "DeepShine Records",
    title: "Alone",
    type: "Releases",
    video: "FKTMZBDzgD8",
    year: 2020
  },
  {
    artists: "Bayza",
    cover: "everythingiwanted",
    dark: false,
    date: "2020-06-05 00:00:00",
    description: "This is an official cover version of the Billie Eilish's hit. Vocals by: Anna Vaverková. Released under One Seven Music in conjunction with FRQNCY.",
    duration: "4:12",
    fanlink: "lnk.bayzamusic.com/everything-i-wanted",
    fanlinkId: "everything-i-wanted",
    fanlinks: {
      "amazon": "https://www.amazon.com/-/es/Bayza/dp/B088HJ2LNZ",
      "amazon-music": "https://music.amazon.com/albums/B088HJ2LNZ",
      "anghami": "https://play.anghami.com/song/76613897",
      "apple": "https://music.apple.com/us/album/everything-i-wanted-single/1512929117?app=music&ls=1",
      "beatport": "https://www.beatport.com/track/everything-i-wanted-original-mix/13602423",
      "deezer": "https://www.deezer.com/en/album/147809492",
      "download": "",
      "itunes": "https://music.apple.com/us/album/everything-i-wanted-single/1512929117?app=itunes&ls=1",
      "soundcloud": "https://soundcloud.com/bayza/everything-i-wanted",
      "spotify": "https://open.spotify.com/album/7u9f8veDrtAZWJDdNKzMiK?si",
      "tidal": "https://tidal.com/browse/album/141154997",
      "tiktok": "https://vm.tiktok.com/J8Xxgfb",
      "youtube": "https://youtu.be/IX2VJo9E_Sw"
    },
    genre: "Deep House",
    id: "everythingiwanted",
    image: "/images/releases/2020/everythingiwanted.jpg",
    label: "One Seven Music / FRQNCY",
    title: "Everything I Wanted",
    type: "Releases",
    video: "IX2VJo9E_Sw",
    year: 2020
  },
  {
    artists: "Noel Kharman",
    cover: "noel-remix",
    dark: false,
    date: "2020-05-02 00:00:00",
    description: "This is a remix for a singer from Lebanon named 'Noel Kharman' who makes Mashups of songs in different languages for youtube. I love his videos and I decided to put my touch on his new mashup 'Desert Roses / انت عمري'.",
    duration: "4:29",
    fanlink: "lnk.bayzamusic.com/desert-rose",
    fanlinkId: "desert-rose",
    fanlinks: {
      bandcamp: "https://bayza.bandcamp.com/track/desert-rose-mashup-bayza-remix",
      download: "https://www.toneden.io/bayza/post/noel-kharman-desert-rose-mashup-bayza-remix",
      soundcloud: "https://soundcloud.com/bayza-bootlegs/desert-rose-enta-omri-mashup-bayza-remix",
      youtube: "https://youtu.be/ONzjgxLeIw4"
    },
    genre: "Deep House",
    id: "desert-rose-enta-omri",
    image: "/images/releases/2020/noel-remix.jpg",
    label: null,
    link: "-bootlegs",
    title: "Desert Rose / انت عمري Mashup (Bayza Remix)",
    type: "Bootlegs/Remixes",
    video: "ONzjgxLeIw4",
    year: 2020
  },
  {
    artists: "INNA",
    cover: "inna-remix",
    dark: false,
    date: "2020-04-22 00:00:00",
    description: "This is a remix for a singer from Romania named 'INNA'. The first time I heard the original song and her voice I loved it and thought it would be nice to remix it.",
    duration: "3:23",
    fanlink: "lnk.bayzamusic.com/not-my-baby",
    fanlinkId: "not-my-baby",
    fanlinks: {
      bandcamp: "https://bayza.bandcamp.com/track/not-my-baby-bayza-remix",
      download: "https://www.toneden.io/bayza/post/inna-not-my-baby-bayza-bootleg",
      soundcloud: "https://soundcloud.com/bayza-bootlegs/not-my-baby-bayza-bootleg",
      youtube: "https://youtu.be/tio93a68b3Q"
    },
    genre: "Deep House",
    id: "not-my-baby",
    image: "/images/releases/2020/inna-remix.jpg",
    label: null,
    link: "-bootlegs",
    title: "Not My Baby (Bayza Bootleg)",
    type: "Bootlegs/Remixes",
    video: "tio93a68b3Q",
    year: 2020
  },
  {
    artists: "Bayza",
    cover: "desires",
    date: "2020-03-27 00:00:00",
    description: "This is my third release under 'DeepShine Records'. It has pleasant sounds and nice melodies with oriental vibes.",
    duration: "3:17",
    fanlink: "fanlink.to/MDS105",
    genre: "Deep House",
    id: "desires",
    label: "DeepShine Records",
    title: "Desires",
    type: "Releases",
    video: "9y9Ja8OCfe4",
    year: 2020
  },
  {
    artists: "Bayza",
    cover: "exaltation",
    date: "2020-03-20 00:00:00",
    description: "I present my second release under 'DeepShine Records'. It's called 'Exaltation' and have some Oriental vibes.",
    duration: "4:21",
    fanlink: "fanlink.to/MDS104",
    genre: "Deep House",
    id: "exaltation",
    label: "DeepShine Records",
    title: "Exaltation",
    type: "Releases",
    video: "yV5G9v3DooE",
    year: 2020
  },
  {
    artists: "Halsey",
    cover: "halsey-remix",
    dark: false,
    date: "2020-02-04 00:00:00",
    description: "Halsey - Still Learning (Bayza Bootleg)",
    duration: "3:55",
    fanlink: "lnk.bayzamusic.com/still-learning",
    fanlinkId: "still-learning",
    fanlinks: {
      bandcamp: "https://bayza.bandcamp.com/track/still-learning-bayza-remix",
      download: "https://www.toneden.io/bayza/post/halsey-still-learning-bayza-bootleg",
      soundcloud: "https://soundcloud.com/bayza-bootlegs/still-learning-bayza-bootleg",
      youtube: "https://youtu.be/AY-P_38wdfM"
    },
    genre: "Deep House",
    id: "still-learning",
    image: "/images/releases/2020/halsey-remix.jpg",
    label: null,
    link: "-bootlegs",
    title: "Still Learning (Bayza Bootleg)",
    type: "Bootlegs/Remixes",
    video: "AY-P_38wdfM",
    year: 2020
  },
  {
    artists: "Bayza & Dimatis",
    cover: "serenity",
    date: "2020-01-24 00:00:00",
    description: "Fusion of styles in collaboration with my brother Dimatis.",
    duration: "3:17",
    fanlink: "dimatis.fanlink.to/serenity",
    genre: "Chill Trap",
    id: "serenity",
    label: null,
    title: "Serenity",
    type: "Releases",
    video: "OMfdAwpKIsc",
    year: 2020
  },
  {
    artists: "Melanie Martinez",
    cover: "melanie-martinez-remix",
    dark: true,
    date: "2020-01-01 00:00:00",
    description: "Melanie Martinez - Strawberry Shortcake (Bayza Bootleg)",
    duration: "3:15",
    fanlink: "lnk.bayzamusic.com/strawberry-shortcake",
    fanlinkId: "strawberry-shortcake",
    fanlinks: {
      bandcamp: "https://bayza.bandcamp.com/track/strawberry-shortcake-bayza-remix",
      download: "https://www.toneden.io/bayza/post/melanie-martinez-strawberry-shortcake-bayza-bootleg",
      soundcloud: "https://soundcloud.com/bayza-bootlegs/strawberry-shortcake-bayza-bootleg",
      youtube: "https://youtu.be/xQHVa1Z6CjI"
    },
    genre: "Deep House",
    id: "strawberry-shortcake",
    image: "/images/releases/2020/melanie-martinez-remix.jpg",
    label: null,
    link: "-bootlegs",
    title: "Strawberry Shortcake (Bayza Bootleg)",
    type: "Bootlegs/Remixes",
    video: "xQHVa1Z6CjI",
    year: 2020
  },
  {
    artists: "Bayza",
    cover: "blossom",
    date: "2019-12-13 00:00:00",
    description: "This is my first release under the label 'DeepShine Records'. Hope you like this Oriental Deep House. :)",
    duration: "4:13",
    fanlink: "fanlink.to/MDS060",
    genre: "Deep House",
    id: "blossom",
    label: "DeepShine Records",
    title: "Blossom",
    type: "Releases",
    video: "oNvLKifFX20",
    year: 2019
  },
  {
    artists: "Bayza",
    cover: "astral",
    date: "2019-12-11 00:00:00",
    description: "This is my first release under the label 'PalmTherapySounds Records'.",
    duration: "4:20",
    fanlink: "lnk.bayzamusic.com/astral",
    genre: "Deep House",
    id: "astral",
    label: "PalmTherapySounds Records",
    title: "Astral",
    type: "Releases",
    video: "japf2Vj4Ohw",
    year: 2019
  },
  {
    artists: "Bayza",
    cover: "mirage",
    dark: false,
    date: "2019-10-25 00:00:00",
    description: "Trying some Psytrance.",
    duration: "4:03",
    fanlink: "lnk.bayzamusic.com/mirage",
    fanlinks: {
      amazon: "https://www.amazon.com/Mirage-Bayza/dp/B07YCMB3WZ/?tag=ton08-20",
      apple: "https://music.apple.com/us/album/mirage-single/1481307126?app=music&ls=1",
      deezer: "https://www.deezer.com/en/album/112510672",
      download: "https://www.toneden.io/bayza/post/bayza-mirage",
      itunes: "https://music.apple.com/us/album/mirage-single/1481307126?app=itunes&ls=1",
      soundcloud: "https://soundcloud.com/bayza/bayza-mirage",
      spotify: "https://open.spotify.com/album/5OnkXwEMSeFykIYCWHNpnm?si",
      youtube: "https://youtu.be/PgVybJcDXTA"
    },
    genre: "Psytrance",
    id: "mirage",
    image: "/images/releases/2019/mirage.jpg",
    label: "Bounce United",
    title: "Mirage",
    type: "Releases",
    video: "PgVybJcDXTA",
    year: 2019
  },
  {
    artists: "Selena Gomez",
    cover: "selena-gomez-remix",
    date: "2019-10-25 00:00:00",
    description: "Selena Gomez - Look At Her Now (Bayza Bootleg)",
    duration: "3:21",
    genre: "Deep House",
    id: "look-at-her-now",
    label: null,
    link: "-bootlegs",
    title: "Look At Her Now (Bayza Bootleg)",
    type: "Bootlegs/Remixes",
    video: "qnGaaOWdnVk",
    year: 2019
  },
  {
    artists: "Charlotte Lawrence",
    cover: "charlotte-remix",
    date: "2019-09-28 00:00:00",
    description: "Charlotte Lawrence - Why Do You Love Me (Bayza Bootleg)",
    duration: "3:13",
    genre: "Deep House",
    id: "why-do-you-love-me",
    label: null,
    link: "-bootlegs",
    title: "Why Do You Love Me (Bayza Bootleg)",
    type: "Bootlegs/Remixes",
    video: "kKDNhycASXw",
    year: 2019
  },
  {
    album: "Genuine",
    artists: "Bayza",
    cover: "genuine-album",
    date: "2019-09-02 00:00:13",
    description: "1. Bayza - Genuine (From Genuine Album)",
    duration: "3:38",
    fanlink: "bayza.fanlink.to/genuine",
    genre: "Deep House",
    id: "genuine",
    label: null,
    title: "Genuine",
    type: "Releases",
    video: "CjtFVqtpBVI",
    year: 2019
  },
  {
    album: "Genuine",
    artists: "Bayza",
    cover: "delirio",
    date: "2019-09-02 00:00:12",
    description: "2. Bayza - Delirio (From Genuine Album)",
    duration: "3:30",
    fanlink: "bayza.fanlink.to/delirio",
    genre: "Deep House",
    id: "delirio",
    label: null,
    title: "Delirio",
    type: "Releases",
    video: "fc2jg7iYBdw",
    year: 2019
  },
  {
    album: "Genuine",
    artists: "Bayza",
    cover: "genuine-album",
    date: "2019-09-02 00:00:11",
    description: "3. Bayza - Romance (From Genuine Album)",
    duration: "3:52",
    fanlink: "bayza.fanlink.to/romance",
    genre: "Deep House",
    id: "romance",
    label: null,
    title: "Romance",
    type: "Releases",
    video: "uZ3JR7YBLPM",
    year: 2019
  },
  {
    album: "Genuine",
    artists: "Bayza",
    cover: "genuine-album",
    date: "2019-09-02 00:00:10",
    description: "4. Bayza - Prisma (From Genuine Album)",
    duration: "3:21",
    fanlink: "bayza.fanlink.to/prisma",
    genre: "Deep House",
    id: "prisma",
    label: null,
    title: "Prisma",
    type: "Releases",
    video: "dZi-BEdfM8M",
    year: 2019
  },
  {
    album: "Genuine",
    artists: "Bayza",
    cover: "genuine-album",
    date: "2019-09-02 00:00:09",
    description: "5. Bayza - Love (From Genuine Album)",
    duration: "2:57",
    fanlink: "bayza.fanlink.to/love",
    genre: "Deep House",
    id: "love",
    label: null,
    title: "Love",
    type: "Releases",
    video: "ufP4BtJzNxY",
    year: 2019
  },
  {
    album: "Genuine",
    artists: "Bayza",
    cover: "genuine-album",
    date: "2019-09-02 00:00:08",
    description: "6. Bayza - Nada (From Genuine Album)",
    duration: "3:44",
    fanlink: "bayza.fanlink.to/nada",
    genre: "Deep House",
    id: "nada",
    label: null,
    title: "Nada",
    type: "Releases",
    video: "Np8ToFBCmS8",
    year: 2019
  },
  {
    album: "Genuine",
    artists: "Bayza",
    cover: "genuine-album",
    date: "2019-09-02 00:00:07",
    description: "7. Bayza - Fell (From Genuine Album)",
    duration: "4:05",
    fanlink: "bayza.fanlink.to/fell",
    genre: "Deep House",
    id: "fell",
    label: null,
    title: "Fell",
    type: "Releases",
    video: "1_5Gmo63J3o",
    year: 2019
  },
  {
    album: "Genuine",
    artists: "Bayza",
    cover: "genuine-album",
    date: "2019-09-02 00:00:06",
    description: "8. Bayza - Crescent (From Genuine Album)",
    duration: "3:42",
    fanlink: "bayza.fanlink.to/crescent",
    genre: "Deep House",
    id: "crescent",
    label: null,
    title: "Crescent",
    type: "Releases",
    video: "GCum26Y36j0",
    year: 2019
  },
  {
    album: "Genuine",
    artists: "Bayza",
    cover: "genuine-album",
    date: "2019-09-02 00:00:05",
    description: "9. Bayza - Praise (From Genuine Album)",
    duration: "3:55",
    fanlink: "bayza.fanlink.to/praise",
    genre: "Deep House",
    id: "praise",
    label: null,
    title: "Praise",
    type: "Releases",
    video: "fErm4Re2Nkw",
    year: 2019
  },
  {
    album: "Genuine",
    artists: "Dimatis & Bayza",
    cover: "genuine-album",
    date: "2019-09-02 00:00:04",
    description: "10. Dimatis & Bayza - Dive (From Genuine Album)",
    duration: "3:47",
    fanlink: "bayza.fanlink.to/dive",
    genre: "Electronic",
    id: "dive",
    label: null,
    title: "Dive",
    type: "Releases",
    video: "0XBB7YWvHYw",
    year: 2019
  },
  {
    album: "Genuine",
    artists: "Bayza",
    cover: "genuine-album",
    date: "2019-09-02 00:00:03",
    description: "11. Bayza - Arousal (From Genuine Album)",
    duration: "3:53",
    fanlink: "bayza.fanlink.to/arousal",
    genre: "Big Room",
    id: "arousal",
    label: null,
    title: "Arousal",
    type: "Releases",
    video: "HFu3uiyun7Y",
    year: 2019
  },
  {
    album: "Genuine",
    artists: "Bayza",
    cover: "genuine-album",
    date: "2019-09-02 00:00:02",
    description: "12. Bayza - Over You (From Genuine Album)",
    duration: "3:53",
    fanlink: "bayza.fanlink.to/over-you",
    genre: "Minimal Bounce",
    id: "over-you",
    label: null,
    title: "Over You",
    type: "Releases",
    video: "qOc0mwJ8KrA",
    year: 2019
  },
  {
    album: "Genuine",
    artists: "Bayza",
    cover: "genuine-album",
    date: "2019-09-02 00:00:02",
    description: "13. Bayza - Zephyr (From Genuine Album)",
    duration: "3:32",
    fanlink: "soundcloud.com/bayza/bayza-zephyr",
    genre: "Dance",
    id: "zephyr",
    label: null,
    title: "Zephyr",
    type: "Releases",
    video: "grVCfUkqjLs",
    year: 2019
  },
  {
    artists: "Shawn Mendes, Camila Cabello",
    cover: "shawn-camila-remix",
    date: "2019-08-03 00:00:00",
    description: "Shawn Mendes, Camila Cabello - Señorita (Bayza Bootleg)",
    duration: "4:32",
    genre: "Deep House",
    id: "senorita",
    label: null,
    link: "-bootlegs",
    title: "Señorita (Bayza Bootleg)",
    type: "Bootlegs/Remixes",
    video: "siGFaPVbS3A",
    year: 2019
  },
  {
    artists: "Bayza",
    cover: "majestic",
    date: "2019-08-02 00:00:00",
    description: "Bayza - Majestic",
    duration: "4:05",
    fanlink: "bayza.fanlink.to/majestic",
    genre: "Melbourne Bounce",
    id: "majestic",
    label: "Nelation",
    title: "Majestic",
    type: "Releases",
    video: "Tfphg1sn1jQ",
    year: 2019
  },
  {
    artists: "Avril Lavigne",
    cover: "avril-remix",
    date: "2019-07-24 00:00:00",
    description: "Avril Lavigne - I Fell In Love With The Devil (Bayza Bootleg)",
    duration: "5:13",
    genre: "Deep House",
    id: "i-fell-in-love-with-the-devil",
    label: null,
    link: "-bootlegs",
    title: "I Fell In Love With The Devil (Bayza Bootleg)",
    type: "Bootlegs/Remixes",
    video: "BWc4wJ7_1dA",
    year: 2019
  },
  {
    artists: "Ronna Riva",
    cover: "ronna-riva-remix",
    date: "2019-07-16 00:00:00",
    description: "Ronna Riva - No Pasa Nada (Bayza Bootleg)",
    duration: "3:43",
    genre: "Deep House",
    id: "no-pasa-nada",
    label: null,
    link: "-bootlegs",
    title: "No Pasa Nada (Bayza Bootleg)",
    type: "Bootlegs/Remixes",
    video: "_qiQqMCPhj8",
    year: 2019
  },
  {
    artists: "Daya",
    cover: "daya-remix",
    date: "2019-06-22 00:00:00",
    description: "Daya - Left Me Yet (Bayza Bootleg)",
    duration: "3:56",
    genre: "Deep House",
    id: "left-me-yet",
    label: null,
    link: "-bootlegs",
    title: "Left Me Yet (Bayza Bootleg)",
    type: "Bootlegs/Remixes",
    video: "HlBlfV3bvYI",
    year: 2019
  },
  {
    artists: "Mabel",
    cover: "mabel-remix",
    date: "2019-06-12 00:00:00",
    description: "Mabel - Mad Love (Bayza Bootleg)",
    duration: "2:56",
    genre: "Deep House",
    id: "mad-love",
    label: null,
    link: "-bootlegs",
    title: "Mad Love (Bayza Bootleg)",
    type: "Bootlegs/Remixes",
    video: "h5k9VCF-WDA",
    year: 2019
  },
  {
    artists: "Lionis",
    cover: "oasis-remix",
    date: "2019-04-19 00:00:00",
    description: "Lionis - Oasis (Bayza Remix)",
    duration: "3:27",
    genre: "Minimal Bounce",
    id: "oasis-remix",
    label: "FREE WAV",
    title: "Oasis (Bayza Remix)",
    type: "Releases",
    video: "uDlypkh80z0",
    year: 2019
  },
  {
    artists: "Bayza",
    cover: "remorse",
    date: "2019-04-11 00:00:00",
    description: "Bayza - Remorse",
    duration: "4:26",
    fanlink: "nelation.lnk.to/remorse",
    genre: "Minimal Bounce",
    id: "remorse",
    label: "Nelation",
    title: "Remorse",
    type: "Releases",
    video: "w83ephnGcf0",
    year: 2019
  },
  {
    artists: "Bayza",
    cover: "wisdom",
    date: "2019-02-13 00:00:00",
    description: "Bayza - Wisdom",
    duration: "4:09",
    fanlink: "nelation.lnk.to/wisdom",
    genre: "Minimal Bounce",
    id: "wisdom",
    label: "Nelation",
    title: "Wisdom",
    type: "Releases",
    video: "lyZyYVHYYC4",
    year: 2019
  },
  {
    artists: "Bayza",
    cover: "not-the-end",
    date: "2018-12-21 00:00:00",
    description: "Bayza - Not The End",
    duration: "4:24",
    fanlink: "bayza.fanlink.to/nottheend",
    genre: "Big Room",
    id: "not-the-end",
    label: null,
    title: "Not The End",
    type: "Releases",
    video: "8t4YBIYjIJQ",
    year: 2018
  },
  {
    artists: "Bayza",
    cover: "tavern",
    date: "2018-11-30 00:00:00",
    description: "Bayza - Tavern",
    duration: "4:41",
    fanlink: "bayza.fanlink.to/tavern",
    genre: "Minimal Bounce",
    id: "tavern",
    label: "Nelation",
    title: "Tavern",
    type: "Releases",
    video: "XM8pl7a9qjc",
    year: 2018
  },
  {
    artists: "Bayza",
    cover: "delight",
    date: "2018-09-05 00:00:00",
    description: "Bayza - Delight",
    duration: "3:58",
    fanlink: "nelation.lnk.to/delight",
    genre: "Melbourne Bounce",
    id: "delight",
    label: "Nelation",
    title: "Delight",
    type: "Releases",
    video: "vPfMCIzlH-Q",
    year: 2018
  },
  {
    artists: "Bayza",
    cover: "abyss",
    date: "2018-06-19 00:00:00",
    description: "Bayza - Abyss",
    duration: "3:55",
    fanlink: "nelation.lnk.to/abyss",
    genre: "Minimal Bounce",
    id: "abyss",
    label: "Nelation",
    title: "Abyss",
    type: "Releases",
    video: "Bnqo9sTgrNA",
    year: 2018
  },
  {
    artists: "Dimatis",
    cover: "timeline-remix",
    date: "2018-06-13 00:00:00",
    description: "Dimatis - Timeline (Bayza Remix)",
    duration: "4:56",
    fanlink: "dimatis.fanlink.to/timelinebayza",
    genre: "Melbourne Bounce",
    id: "timeline-remix",
    label: null,
    title: "Timeline (Bayza Remix)",
    type: "Releases",
    video: "gueXauiEUkM",
    year: 2018
  },
  {
    artists: "Bayza",
    cover: "aether",
    date: "2018-05-24 00:00:00",
    description: "Bayza - Aether",
    duration: "4:26",
    fanlink: "nelation.lnk.to/aether",
    genre: "Melbourne Bounce",
    id: "aether",
    label: "Nelation",
    title: "Aether",
    type: "Releases",
    video: "ihtWiAPXhYY",
    year: 2018
  },
  {
    artists: "Bayza",
    cover: "endurance",
    date: "2018-05-16 00:00:00",
    description: "Bayza - Endurance",
    duration: "4:56",
    fanlink: "nelation.lnk.to/endurance",
    genre: "Melbourne Bounce",
    id: "endurance",
    label: "Nelation",
    title: "Endurance",
    type: "Releases",
    video: "ZzcCuoYjC6Q",
    year: 2018
  },
  {
    artists: "Bayza",
    cover: "convergence",
    date: "2018-04-23 00:00:00",
    description: "Bayza - Convergence",
    duration: "4:30",
    fanlink: "nelation.lnk.to/convergence",
    genre: "Melbourne Bounce",
    id: "convergence",
    label: "Nelation",
    title: "Convergence",
    type: "Releases",
    video: "QYLnqujS8Uk",
    year: 2018
  },
  {
    artists: "Bayza",
    cover: "unchained",
    date: "2018-03-13 00:00:00",
    description: "Bayza - Unchained",
    duration: "4:30",
    genre: "Big Room",
    id: "unchained",
    label: null,
    title: "Unchained",
    type: "Releases",
    video: "89-GLf29wiw",
    year: 2018
  }
];
