export const tracks = [
  {
    "fanlink": "dimatis.fanlink.to/serenity",
    "description": "Fusion of styles in collaboration with my brother Dimatis.",
    "title": "Serenity",
    "type": "Releases",
    "year": 2020,
    "cover": "serenity",
    "label": null,
    "duration": "3:17",
    "video": "OMfdAwpKIsc",
    "artists": "Bayza & Dimatis",
    "date": "2020-01-24 00:00:00",
    "release": "serenity",
    "genre": "Chill Trap"
  },
  {
    "fanlink": "fanlink.to/MDS060",
    "description": "This is my first release under the label 'DeepShine Records'. Hope you like this Oriental Deep House. :)",
    "title": "Blossom",
    "type": "Releases",
    "year": 2019,
    "cover": "blossom",
    "label": "DeepShine Records",
    "duration": "4:13",
    "video": "oNvLKifFX20",
    "artists": "Bayza",
    "date": "2019-12-13 00:00:00",
    "release": "blossom",
    "genre": "Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/astral",
    "description": "This is my first release under the label 'PalmTherapySounds Records'.",
    "title": "Astral",
    "type": "Releases",
    "year": 2019,
    "cover": "astral",
    "label": "PalmTherapySounds Records",
    "duration": "4:20",
    "video": "japf2Vj4Ohw",
    "artists": "Bayza",
    "date": "2019-12-11 00:00:00",
    "release": "astral",
    "genre": "Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/mirage",
    "description": "Trying some Psytrance.",
    "title": "Mirage",
    "type": "Releases",
    "year": 2019,
    "cover": "mirage",
    "label": "Bounce United",
    "duration": "4:03",
    "video": "PgVybJcDXTA",
    "artists": "Bayza",
    "date": "2019-10-25 00:00:00",
    "release": "mirage",
    "genre": "Psytrance"
  },
  {
    "album": "Genuine",
    "fanlink": "bayza.fanlink.to/genuine",
    "description": "1. Bayza - Genuine (From Genuine Album)",
    "title": "Genuine",
    "type": "Releases",
    "year": 2019,
    "cover": "genuine-album",
    "label": null,
    "duration": "3:38",
    "video": "CjtFVqtpBVI",
    "artists": "Bayza",
    "date": "2019-09-02 00:00:13",
    "release": "genuine",
    "genre": "Deep House"
  },
  {
    "album": "Genuine",
    "fanlink": "bayza.fanlink.to/delirio",
    "description": "2. Bayza - Delirio (From Genuine Album)",
    "title": "Delirio",
    "type": "Releases",
    "year": 2019,
    "cover": "delirio",
    "label": null,
    "duration": "3:30",
    "video": "fc2jg7iYBdw",
    "artists": "Bayza",
    "date": "2019-09-02 00:00:12",
    "release": "delirio",
    "genre": "Deep House"
  },
  {
    "album": "Genuine",
    "fanlink": "bayza.fanlink.to/romance",
    "description": "3. Bayza - Romance (From Genuine Album)",
    "title": "Romance",
    "type": "Releases",
    "year": 2019,
    "cover": "genuine-album",
    "label": null,
    "duration": "3:52",
    "video": "uZ3JR7YBLPM",
    "artists": "Bayza",
    "date": "2019-09-02 00:00:11",
    "release": "romance",
    "genre": "Deep House"
  },
  {
    "album": "Genuine",
    "fanlink": "bayza.fanlink.to/prisma",
    "description": "4. Bayza - Prisma (From Genuine Album)",
    "title": "Prisma",
    "type": "Releases",
    "year": 2019,
    "cover": "genuine-album",
    "label": null,
    "duration": "3:21",
    "video": "dZi-BEdfM8M",
    "artists": "Bayza",
    "date": "2019-09-02 00:00:10",
    "release": "prisma",
    "genre": "Deep House"
  },
  {
    "album": "Genuine",
    "fanlink": "bayza.fanlink.to/love",
    "description": "5. Bayza - Love (From Genuine Album)",
    "title": "Love",
    "type": "Releases",
    "year": 2019,
    "cover": "genuine-album",
    "label": null,
    "duration": "2:57",
    "video": "ufP4BtJzNxY",
    "artists": "Bayza",
    "date": "2019-09-02 00:00:09",
    "release": "love",
    "genre": "Deep House"
  },
  {
    "album": "Genuine",
    "fanlink": "bayza.fanlink.to/nada",
    "description": "6. Bayza - Nada (From Genuine Album)",
    "title": "Nada",
    "type": "Releases",
    "year": 2019,
    "cover": "genuine-album",
    "label": null,
    "duration": "3:44",
    "video": "Np8ToFBCmS8",
    "artists": "Bayza",
    "date": "2019-09-02 00:00:08",
    "release": "nada",
    "genre": "Deep House"
  },
  {
    "album": "Genuine",
    "fanlink": "bayza.fanlink.to/fell",
    "description": "7. Bayza - Fell (From Genuine Album)",
    "title": "Fell",
    "type": "Releases",
    "year": 2019,
    "cover": "genuine-album",
    "label": null,
    "duration": "4:05",
    "video": "1_5Gmo63J3o",
    "artists": "Bayza",
    "date": "2019-09-02 00:00:07",
    "release": "fell",
    "genre": "Deep House"
  },
  {
    "album": "Genuine",
    "fanlink": "bayza.fanlink.to/crescent",
    "description": "8. Bayza - Crescent (From Genuine Album)",
    "title": "Crescent",
    "type": "Releases",
    "year": 2019,
    "cover": "genuine-album",
    "label": null,
    "duration": "3:42",
    "video": "GCum26Y36j0",
    "artists": "Bayza",
    "date": "2019-09-02 00:00:06",
    "release": "crescent",
    "genre": "Deep House"
  },
  {
    "album": "Genuine",
    "fanlink": "bayza.fanlink.to/praise",
    "description": "9. Bayza - Praise (From Genuine Album)",
    "title": "Praise",
    "type": "Releases",
    "year": 2019,
    "cover": "genuine-album",
    "label": null,
    "duration": "3:55",
    "video": "fErm4Re2Nkw",
    "artists": "Bayza",
    "date": "2019-09-02 00:00:05",
    "release": "praise",
    "genre": "Deep House"
  },
  {
    "album": "Genuine",
    "fanlink": "bayza.fanlink.to/dive",
    "description": "10. Dimatis & Bayza - Dive (From Genuine Album)",
    "title": "Dive",
    "type": "Releases",
    "year": 2019,
    "cover": "genuine-album",
    "label": null,
    "duration": "3:47",
    "video": "0XBB7YWvHYw",
    "artists": "Dimatis & Bayza",
    "date": "2019-09-02 00:00:04",
    "release": "dive",
    "genre": "Electronic"
  },
  {
    "album": "Genuine",
    "fanlink": "bayza.fanlink.to/arousal",
    "description": "11. Bayza - Arousal (From Genuine Album)",
    "title": "Arousal",
    "type": "Releases",
    "year": 2019,
    "cover": "genuine-album",
    "label": null,
    "duration": "3:53",
    "video": "HFu3uiyun7Y",
    "artists": "Bayza",
    "date": "2019-09-02 00:00:03",
    "release": "arousal",
    "genre": "Big Room"
  },
  {
    "album": "Genuine",
    "fanlink": "bayza.fanlink.to/over-you",
    "description": "12. Bayza - Over You (From Genuine Album)",
    "title": "Over You",
    "type": "Releases",
    "year": 2019,
    "cover": "genuine-album",
    "label": null,
    "duration": "3:53",
    "video": "qOc0mwJ8KrA",
    "artists": "Bayza",
    "date": "2019-09-02 00:00:02",
    "release": "over-you",
    "genre": "Minimal Bounce"
  },
  {
    "album": "Genuine",
    "fanlink": "soundcloud.com/bayza/bayza-zephyr",
    "description": "13. Bayza - Zephyr (From Genuine Album)",
    "title": "Zephyr",
    "type": "Releases",
    "year": 2019,
    "cover": "genuine-album",
    "label": null,
    "duration": "3:32",
    "video": "grVCfUkqjLs",
    "artists": "Bayza",
    "date": "2019-09-02 00:00:02",
    "release": "zephyr",
    "genre": "Dance"
  },
  {
    "fanlink": "bayza.fanlink.to/majestic",
    "description": "Bayza - Majestic",
    "title": "Majestic",
    "type": "Releases",
    "year": 2019,
    "cover": "majestic",
    "label": "Nelation",
    "duration": "4:05",
    "video": "Tfphg1sn1jQ",
    "artists": "Bayza",
    "date": "2019-08-02 00:00:00",
    "release": "majestic",
    "genre": "Melbourne Bounce"
  },
  {
    "description": "Lionis - Oasis (Bayza Remix)",
    "title": "Oasis (Bayza Remix)",
    "type": "Releases",
    "year": 2019,
    "cover": "oasis-remix",
    "label": "FREE WAV",
    "duration": "3:27",
    "video": "uDlypkh80z0",
    "artists": "Lionis",
    "date": "2019-04-19 00:00:00",
    "release": "oasis-remix",
    "genre": "Minimal Bounce"
  },
  {
    "fanlink": "nelation.lnk.to/remorse",
    "description": "Bayza - Remorse",
    "title": "Remorse",
    "type": "Releases",
    "year": 2019,
    "cover": "remorse",
    "label": "Nelation",
    "duration": "4:26",
    "video": "w83ephnGcf0",
    "artists": "Bayza",
    "date": "2019-04-11 00:00:00",
    "release": "remorse",
    "genre": "Minimal Bounce"
  },
  {
    "fanlink": "nelation.lnk.to/wisdom",
    "description": "Bayza - Wisdom",
    "title": "Wisdom",
    "type": "Releases",
    "year": 2019,
    "cover": "wisdom",
    "label": "Nelation",
    "duration": "4:09",
    "video": "lyZyYVHYYC4",
    "artists": "Bayza",
    "date": "2019-02-13 00:00:00",
    "release": "wisdom",
    "genre": "Minimal Bounce"
  },
  {
    "fanlink": "lnk.bayzamusic.com/still-learning",
    "description": "Halsey - Still Learning (Bayza Bootleg)",
    "title": "Still Learning (Bayza Bootleg)",
    "type": "Bootlegs/Remixes",
    "year": 2020,
    "cover": "halsey-remix",
    "label": null,
    "duration": "3:55",
    "video": "AY-P_38wdfM",
    "artists": "Halsey",
    "date": "2020-02-04 00:00:00",
    "release": "still-learning",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "fanlink": "lnk.bayzamusic.com/strawberry-shortcake",
    "description": "Melanie Martinez - Strawberry Shortcake (Bayza Bootleg)",
    "title": "Strawberry Shortcake (Bayza Bootleg)",
    "type": "Bootlegs/Remixes",
    "year": 2020,
    "cover": "melanie-martinez-remix",
    "label": null,
    "duration": "3:15",
    "video": "xQHVa1Z6CjI",
    "artists": "Melanie Martinez",
    "date": "2020-01-01 00:00:00",
    "release": "strawberry-shortcake",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "description": "Selena Gomez - Look At Her Now (Bayza Bootleg)",
    "title": "Look At Her Now (Bayza Bootleg)",
    "type": "Bootlegs/Remixes",
    "year": 2019,
    "cover": "selena-gomez-remix",
    "label": null,
    "duration": "3:21",
    "video": "qnGaaOWdnVk",
    "artists": "Selena Gomez",
    "date": "2019-10-25 00:00:00",
    "release": "look-at-her-now",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "description": "Charlotte Lawrence - Why Do You Love Me (Bayza Bootleg)",
    "title": "Why Do You Love Me (Bayza Bootleg)",
    "type": "Bootlegs/Remixes",
    "year": 2019,
    "cover": "charlotte-remix",
    "label": null,
    "duration": "3:13",
    "video": "kKDNhycASXw",
    "artists": "Charlotte Lawrence",
    "date": "2019-09-28 00:00:00",
    "release": "why-do-you-love-me",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "description": "Shawn Mendes, Camila Cabello - Se\u00f1orita (Bayza Bootleg)",
    "title": "Se\u00f1orita (Bayza Bootleg)",
    "type": "Bootlegs/Remixes",
    "year": 2019,
    "cover": "shawn-camila-remix",
    "label": null,
    "duration": "4:32",
    "video": "siGFaPVbS3A",
    "artists": "Shawn Mendes, Camila Cabello",
    "date": "2019-08-03 00:00:00",
    "release": "senorita",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "description": "Avril Lavigne - I Fell In Love With The Devil (Bayza Bootleg)",
    "title": "I Fell In Love With The Devil (Bayza Bootleg)",
    "type": "Bootlegs/Remixes",
    "year": 2019,
    "cover": "avril-remix",
    "label": null,
    "duration": "5:13",
    "video": "BWc4wJ7_1dA",
    "artists": "Avril Lavigne",
    "date": "2019-07-24 00:00:00",
    "release": "i-fell-in-love-with-the-devil",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "description": "Ronna Riva - No Pasa Nada (Bayza Bootleg)",
    "title": "No Pasa Nada (Bayza Bootleg)",
    "type": "Bootlegs/Remixes",
    "year": 2019,
    "cover": "ronna-riva-remix",
    "label": null,
    "duration": "3:43",
    "video": "_qiQqMCPhj8",
    "artists": "Ronna Riva",
    "date": "2019-07-16 00:00:00",
    "release": "no-pasa-nada",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "description": "Daya - Left Me Yet (Bayza Bootleg)",
    "title": "Left Me Yet (Bayza Bootleg)",
    "type": "Bootlegs/Remixes",
    "year": 2019,
    "cover": "daya-remix",
    "label": null,
    "duration": "3:56",
    "video": "HlBlfV3bvYI",
    "artists": "Daya",
    "date": "2019-06-22 00:00:00",
    "release": "left-me-yet",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "description": "Mabel - Mad Love (Bayza Bootleg)",
    "title": "Mad Love (Bayza Bootleg)",
    "type": "Bootlegs/Remixes",
    "year": 2019,
    "cover": "mabel-remix",
    "label": null,
    "duration": "2:56",
    "video": "h5k9VCF-WDA",
    "artists": "Mabel",
    "date": "2019-06-12 00:00:00",
    "release": "mad-love",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "fanlink": "bayza.fanlink.to/nottheend",
    "description": "Bayza - Not The End",
    "title": "Not The End",
    "type": "Releases",
    "year": 2018,
    "cover": "not-the-end",
    "label": null,
    "duration": "4:24",
    "video": "8t4YBIYjIJQ",
    "artists": "Bayza",
    "date": "2018-12-21 00:00:00",
    "release": "not-the-end",
    "genre": "Big Room"
  },
  {
    "fanlink": "bayza.fanlink.to/tavern",
    "description": "Bayza - Tavern",
    "title": "Tavern",
    "type": "Releases",
    "year": 2018,
    "cover": "tavern",
    "label": "Nelation",
    "duration": "4:41",
    "video": "XM8pl7a9qjc",
    "artists": "Bayza",
    "date": "2018-11-30 00:00:00",
    "release": "tavern",
    "genre": "Minimal Bounce"
  },
  {
    "fanlink": "nelation.lnk.to/delight",
    "description": "Bayza - Delight",
    "title": "Delight",
    "type": "Releases",
    "year": 2018,
    "cover": "delight",
    "label": "Nelation",
    "duration": "3:58",
    "video": "vPfMCIzlH-Q",
    "artists": "Bayza",
    "date": "2018-09-05 00:00:00",
    "release": "delight",
    "genre": "Melbourne Bounce"
  },
  {
    "fanlink": "nelation.lnk.to/abyss",
    "description": "Bayza - Abyss",
    "title": "Abyss",
    "type": "Releases",
    "year": 2018,
    "cover": "abyss",
    "label": "Nelation",
    "duration": "3:55",
    "video": "Bnqo9sTgrNA",
    "artists": "Bayza",
    "date": "2018-06-19 00:00:00",
    "release": "abyss",
    "genre": "Minimal Bounce"
  },
  {
    "fanlink": "dimatis.fanlink.to/timelinebayza",
    "description": "Dimatis - Timeline (Bayza Remix)",
    "title": "Timeline (Bayza Remix)",
    "type": "Releases",
    "year": 2018,
    "cover": "timeline-remix",
    "label": null,
    "duration": "4:56",
    "video": "gueXauiEUkM",
    "artists": "Dimatis",
    "date": "2018-06-13 00:00:00",
    "release": "timeline-remix",
    "genre": "Melbourne Bounce"
  },
  {
    "fanlink": "nelation.lnk.to/aether",
    "description": "Bayza - Aether",
    "title": "Aether",
    "type": "Releases",
    "year": 2018,
    "cover": "aether",
    "label": "Nelation",
    "duration": "4:26",
    "video": "ihtWiAPXhYY",
    "artists": "Bayza",
    "date": "2018-05-24 00:00:00",
    "release": "aether",
    "genre": "Melbourne Bounce"
  },
  {
    "fanlink": "nelation.lnk.to/endurance",
    "description": "Bayza - Endurance",
    "title": "Endurance",
    "type": "Releases",
    "year": 2018,
    "cover": "endurance",
    "label": "Nelation",
    "duration": "4:56",
    "video": "ZzcCuoYjC6Q",
    "artists": "Bayza",
    "date": "2018-05-16 00:00:00",
    "release": "endurance",
    "genre": "Melbourne Bounce"
  },
  {
    "fanlink": "nelation.lnk.to/convergence",
    "description": "Bayza - Convergence",
    "title": "Convergence",
    "type": "Releases",
    "year": 2018,
    "cover": "convergence",
    "label": "Nelation",
    "duration": "4:30",
    "video": "QYLnqujS8Uk",
    "artists": "Bayza",
    "date": "2018-04-23 00:00:00",
    "release": "convergence",
    "genre": "Melbourne Bounce"
  },
  {
    "description": "Bayza - Unchained",
    "title": "Unchained",
    "type": "Releases",
    "year": 2018,
    "cover": "unchained",
    "label": null,
    "duration": "4:30",
    "video": "89-GLf29wiw",
    "artists": "Bayza",
    "date": "2018-03-13 00:00:00",
    "release": "unchained",
    "genre": "Big Room"
  },
  {
    "fanlink": "fanlink.to/MDS104",
    "description": "I present my second release under 'DeepShine Records'. It's called 'Exaltation' and have some Oriental vibes.",
    "title": "Exaltation",
    "type": "Releases",
    "year": 2020,
    "cover": "exaltation",
    "label": "DeepShine Records",
    "duration": "4:21",
    "video": "yV5G9v3DooE",
    "artists": "Bayza",
    "date": "2020-03-20 00:00:00",
    "release": "exaltation",
    "genre": "Deep House"
  },
  {
    "fanlink": "fanlink.to/MDS105",
    "description": "This is my third release under 'DeepShine Records'. It has pleasant sounds and nice melodies with oriental vibes.",
    "title": "Desires",
    "type": "Releases",
    "year": 2020,
    "cover": "desires",
    "label": "DeepShine Records",
    "duration": "3:17",
    "video": "9y9Ja8OCfe4",
    "artists": "Bayza",
    "date": "2020-03-27 00:00:00",
    "release": "desires",
    "genre": "Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/not-my-baby",
    "description": "This is a remix for a singer from Romania named 'INNA'. The first time I heard the original song and her voice I loved it and thought it would be nice to remix it.",
    "title": "Not My Baby (Bayza Bootleg)",
    "type": "Bootlegs/Remixes",
    "year": 2020,
    "cover": "inna-remix",
    "label": null,
    "duration": "3:23",
    "video": "tio93a68b3Q",
    "artists": "INNA",
    "date": "2020-04-22 00:00:00",
    "release": "not-my-baby",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "fanlink": "lnk.bayzamusic.com/desert-rose",
    "description": "This is a remix for a singer from Lebanon named 'Noel Kharman' who makes Mashups of songs in different languages for youtube. I love his videos and I decided to put my touch on his new mashup 'Desert Roses / \u0627\u0646\u062a \u0639\u0645\u0631\u064a'.",
    "title": "Desert Rose / \u0627\u0646\u062a \u0639\u0645\u0631\u064a Mashup (Bayza Remix)",
    "type": "Bootlegs/Remixes",
    "year": 2020,
    "cover": "noel-remix",
    "label": null,
    "duration": "4:29",
    "video": "ONzjgxLeIw4",
    "artists": "Noel Kharman",
    "date": "2020-05-02 00:00:00",
    "release": "desert-rose-enta-omri",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "fanlink": "lnk.bayzamusic.com/everything-i-wanted",
    "description": "This is an official cover version of the Billie Eilish's hit. Vocals by: Anna Vaverkov\u00e1. Released under One Seven Music in conjunction with FRQNCY.",
    "title": "Everything I Wanted",
    "type": "Releases",
    "year": 2020,
    "cover": "everythingiwanted",
    "label": "One Seven Music / FRQNCY",
    "duration": "4:12",
    "video": "IX2VJo9E_Sw",
    "artists": "Bayza",
    "date": "2020-06-05 00:00:00",
    "release": "everythingiwanted",
    "genre": "Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/alone",
    "description": "My fourth release under DeepShine Records. This time in collaboration with Moroccan producer DJ SK.",
    "title": "Alone",
    "type": "Releases",
    "year": 2020,
    "cover": "alone",
    "label": "DeepShine Records",
    "duration": "4:24",
    "video": "FKTMZBDzgD8",
    "artists": "DJ SK & Bayza",
    "date": "2020-06-24 00:00:00",
    "release": "alone",
    "genre": "Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/miracle",
    "description": "A Miracle is an effect or extraordinary event not explicable by natural, scientific law. It also characterizes any beneficial event that is statistically improbable, and some coincidences can bee seen as miracles.",
    "title": "Miracle",
    "type": "Releases",
    "year": 2020,
    "cover": "miracle",
    "label": null,
    "duration": "3:12",
    "video": "-vx3oZ4j4h0",
    "artists": "Bayza",
    "date": "2020-07-10 00:00:00",
    "release": "miracle",
    "genre": "Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/make-believe",
    "description": "I was participating in a remix competition for \"Eress - Make Believe\" and I won the first place. :)",
    "title": "Make Believe (Bayza Remix)",
    "type": "Releases",
    "year": 2020,
    "cover": "make-believe-remix",
    "label": null,
    "duration": "4:28",
    "video": "MjaLp6MNm4g",
    "artists": "Eress",
    "date": "2020-08-01 00:00:00",
    "release": "make-believe",
    "genre": "Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/solace",
    "description": "Bayza is back on PalmTherapySounds with his track \"Solace\".",
    "title": "Solace",
    "type": "Releases",
    "year": 2020,
    "cover": "solace",
    "label": "PalmTherapySounds",
    "duration": "3:52",
    "video": "oYqe05-Aha0",
    "artists": "Bayza",
    "date": "2020-08-28 00:00:00",
    "release": "solace",
    "genre": "Deep House"
  },
  {
    "fanlink": "bayzamusic.com/fire-drill",
    "description": "There was some people of Melanie Martinez's community that came to my 'Strawberry Shortcake' Remix and they gave positive comments and wanted me to make more of Melanie. I present this time a remix for 'Fire Drill' Hope you like it.",
    "title": "Fire Drill (Bayza Bootleg)",
    "type": "Bootlegs/Remixes",
    "year": 2020,
    "cover": "fire-drill",
    "label": null,
    "duration": "4:25",
    "video": "kYNUcObW_H0",
    "artists": "Melanie Martinez",
    "date": "2020-09-18 00:00:00",
    "release": "fire-drill",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "fanlink": "lnk.bayzamusic.com/hold-on-to-me",
    "description": "This track is different from my usual style because it is a collaboration with my twin brother Dimatis, he is a Melodic Dubstep producer. We don't collaborate so often, but when we do, we create styles that are different from both of us. This time we try some Future Bass with vocals. Hope you like it!",
    "title": "Hold On To Me",
    "type": "Releases",
    "year": 2020,
    "cover": "hold-on-to-me",
    "label": null,
    "duration": "3:27",
    "video": "N2sZKeX_xGI",
    "artists": "Dimatis & Bayza",
    "date": "2020-09-25 00:00:00",
    "release": "hold-on-to-me",
    "genre": "Future Bass"
  },
  {
    "fanlink": "lnk.bayzamusic.com/no-guarantee",
    "description": "There is just no guarantee, for you and me...",
    "title": "No Guarantee",
    "type": "Releases",
    "year": 2020,
    "cover": "no-guarantee",
    "label": "DeepShine Records",
    "duration": "3:38",
    "video": "YPLPc6xGWK4",
    "artists": "Bayza",
    "date": "2020-10-19 00:00:00",
    "release": "no-guarantee",
    "genre": "Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/reborn",
    "description": "We made this track for a gaming community here in Panama. It's like a Trap style, hope you enjoy!.",
    "title": "Reborn",
    "type": "Releases",
    "year": 2020,
    "cover": "reborn",
    "label": null,
    "duration": "2:42",
    "video": "Uqm00tl0nKQ",
    "artists": "Bayza & Dimatis",
    "date": "2020-10-22 00:00:00",
    "release": "reborn",
    "genre": "Trap"
  },
  {
    "fanlink": "lnk.bayzamusic.com/lamentos",
    "description": "I had the idea to create a dark, mysterious, and somewhat scary Halloween-themed track for October 31. And here it is, hope you like it!",
    "title": "Lamentos",
    "type": "Releases",
    "year": 2020,
    "cover": "lamentos",
    "label": null,
    "duration": "3:36",
    "video": "nQ0A1WWxuFY",
    "artists": "Bayza",
    "date": "2020-10-31 00:00:00",
    "release": "lamentos",
    "genre": "Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/LVAO",
    "description": "I loved Billie Eilish and ROSAL\u00cdA collaboration. I was amazed to hear Billie singing in my language (spanish). Since first time listening to it I felt that I had to remix it with my deep vibe.",
    "title": "Lo Vas A Olvidar (Bayza Remix)",
    "type": "Bootlegs/Remixes",
    "year": 2021,
    "cover": "lo-vas-a-olvidar",
    "label": null,
    "duration": "3:28",
    "video": "RilJRFTno6M",
    "artists": "Billie Eilish, ROSAL\u00cdA",
    "date": "2021-01-22 00:00:00",
    "release": "lo-vas-a-olvidar",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "fanlink": "lnk.bayzamusic.com/LookingAtYou",
    "description": "Starting 2021 with some deep and slappy stuff!",
    "title": "Looking At You",
    "type": "Releases",
    "year": 2021,
    "cover": "looking-at-you",
    "label": null,
    "duration": "3:18",
    "video": "Yd5LZuOyCpg",
    "artists": "Bayza",
    "date": "2021-02-12 00:00:00",
    "release": "looking-at-you",
    "genre": "Deep House / Slap House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/my-head-my-heart",
    "description": "Ava Max - My Head & My Heart (Bayza Remix)",
    "title": "My Head & My Heart (Bayza Remix)",
    "type": "Bootlegs/Remixes",
    "year": 2021,
    "cover": "my-head-my-heart",
    "label": null,
    "duration": "3:33",
    "video": "eKGxQxm9FUA",
    "artists": "Ava Max",
    "date": "2021-02-16 00:00:00",
    "release": "my-head-my-heart",
    "genre": "Deep House",
    "link": "-bootlegs"
  },
  {
    "fanlink": "lnk.bayzamusic.com/without-you",
    "description": "Releasing some chill deep house with DeepShine Records!",
    "title": "Without You",
    "type": "Releases",
    "year": 2021,
    "cover": "without-you",
    "label": null,
    "duration": "2:47",
    "video": "Ncxok5G7yOA",
    "artists": "Bayza",
    "date": "2021-03-08 00:00:00",
    "release": "without-you",
    "genre": "Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/YouSaidGoodbye",
    "description": "This time I worked with a Romanian singer named \"Giulia Mihai\". She wrote the lyrics and provided her voice for this song. The song is kinda sad/melancholic with lyrics in English and Spanish language.",
    "title": "You Said Goodbye",
    "type": "Releases",
    "year": 2021,
    "cover": "you-said-goodbye",
    "label": "DeepShine Records",
    "duration": "3:19",
    "video": "5Pt9qzAqVxA",
    "artists": "Bayza feat. Giulia Mihai",
    "date": "2021-03-31 00:00:00",
    "release": "you-said-goodbye",
    "genre": "Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/FeelSoLonely",
    "description": "Fresh dance/house tune \"Feel So Lonely\" is OUT!",
    "title": "Feel So Lonely",
    "type": "Releases",
    "year": 2021,
    "cover": "feel-so-lonely",
    "label": "FRQNCY",
    "duration": "2:48",
    "video": "q-UK_m9rq3Q",
    "artists": "Bayza",
    "date": "2021-04-16 00:00:00",
    "release": "feel-so-lonely",
    "genre": "Slap House / Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/Feels",
    "description": "Fresh chill house track in collaboration with Finnish producer \"DeejaVu\".",
    "title": "Feels",
    "type": "Releases",
    "year": 2021,
    "cover": "feels",
    "label": null,
    "duration": "2:46",
    "video": "hWhQJKLyyss",
    "artists": "DeejaVu X Bayza",
    "date": "2021-04-23 00:00:00",
    "release": "feels",
    "genre": "Deep House / Chill House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/TakeMeHome",
    "description": "Bayza brings \"Take Me Home\" under the German label \"The Night Drive\". The inspiration for this track was to try to transmit nighty vibes that are suited perfectly for car driving or club parties because of its modern house music style.",
    "title": "Take Me Home",
    "type": "Releases",
    "year": 2021,
    "cover": "take-me-home",
    "label": "The Night Drive",
    "duration": "2:58",
    "video": "BwKO7sfFVAA",
    "artists": "Bayza",
    "date": "2021-06-25 00:00:00",
    "release": "take-me-home",
    "genre": "Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/ThumbsRemix",
    "description": "Hi guys, I hope you like this track, someone asked me to remix Thumbs by Sabrina Carpenter, I liked the original song when I first listened to it so I decided to finish this remix. I've also uploaded an <a class=\"text-white\" href=\"https://www.youtube.com/watch?v=9u_UwD-WpSE\" target=\"_blank\" title=\"Bayza - Thumbs | Instrumental Version\">Instrumental Version</a></b> for those who want to listen without the vocals.",
    "title": "Thumbs (Bayza Remix)",
    "type": "Bootlegs/Remixes",
    "year": 2021,
    "cover": "thumbs",
    "label": null,
    "duration": "3:23",
    "video": "SPlamGgkl00",
    "artists": "Sabrina Carpenter",
    "date": "2021-12-02 00:00:00",
    "release": "thumbs-remix",
    "genre": "Dance",
    "link": "-bootlegs"
  },
  {
    "fanlink": "lnk.bayzamusic.com/Pirhan",
    "description": null,
    "title": "Pirhan",
    "type": "Releases",
    "year": 2021,
    "cover": "pirhan",
    "label": "Ario Records",
    "duration": "4:55",
    "video": "_HNN88li9kI",
    "artists": "DJ Phellix, Bayza, Sheenubb ft. Sant",
    "date": "2021-12-15 00:00:00",
    "release": "pirhan",
    "genre": "Organic House / Deep House"
  },
  {
    "album": "Passages",
    "fanlink": "lnk.bayzamusic.com/DesertRose",
    "description": "This is the instrumental version of \"<a class=\"text-white\" href=\"https://bayzamusic.com/releases/2020-bootlegs/desert-rose-enta-omri\" target=\"_blank\" title=\"Noel Kharman - Desert Rose / \u0627\u0646\u062a \u0639\u0645\u0631\u064a Mashup (Bayza Remix)\">Noel Kharman - Desert Rose / \u0627\u0646\u062a \u0639\u0645\u0631\u064a Mashup (Bayza Remix)</a>\"",
    "title": "Desert Rose - Instrumental",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "passages",
    "label": null,
    "duration": "3:49",
    "video": "h1aLkuT0ctI",
    "year": 2021,
    "date": "2021-12-30 00:00:01",
    "release": "desert-rose",
    "genre": "Deep House"
  },
  {
    "album": "Passages",
    "fanlink": "lnk.bayzamusic.com/NotMyBaby",
    "description": "This is the instrumental version of \"<a class=\"text-white\" href=\"https://bayzamusic.com/releases/2020-bootlegs/not-my-baby\" target=\"_blank\" title=\"INNA - Not My Baby (Bayza Bootleg)\">INNA - Not My Baby (Bayza Bootleg)</a>\"",
    "title": "Not My Baby - Instrumental",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "passages",
    "label": null,
    "duration": "3:19",
    "video": "KIP1Wa8lEsk",
    "year": 2021,
    "date": "2021-12-30 00:00:02",
    "release": "notmybaby",
    "genre": "Deep House"
  },
  {
    "album": "Passages",
    "fanlink": "lnk.bayzamusic.com/MyHeadMyHeart",
    "description": "This is the instrumental version of \"<a class=\"text-white\" href=\"https://bayzamusic.com/releases/2021-bootlegs/my-head-my-heart\" target=\"_blank\" title=\"Ava Max - My Head & My Heart (Bayza Bootleg)\">Ava Max - My Head & My Heart (Bayza Bootleg)</a>\"",
    "title": "My Head & My Heart - Instrumental",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "passages",
    "label": null,
    "duration": "3:31",
    "video": "JaN96BTWzZo",
    "year": 2021,
    "date": "2021-12-30 00:00:03",
    "release": "myheadmyheart",
    "genre": "Deep House"
  },
  {
    "album": "Passages",
    "fanlink": "lnk.bayzamusic.com/LoVasAOlvidar",
    "description": "This is the instrumental version of \"<a class=\"text-white\" href=\"https://bayzamusic.com/releases/2021-bootlegs/lo-vas-a-olvidar\" target=\"_blank\" title=\"Billie Eilish, ROSAL\u00cdA - Lo Vas A Olvidar (Bayza Bootleg)\">Billie Eilish, ROSAL\u00cdA - Lo Vas A Olvidar (Bayza Bootleg)</a>\"",
    "title": "Lo Vas A Olvidar - Instrumental",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "passages",
    "label": null,
    "duration": "3:18",
    "video": "VXXsLZm3HVc",
    "year": 2021,
    "date": "2021-12-30 00:00:04",
    "release": "lovasaolvidar",
    "genre": "Deep House"
  },
  {
    "album": "Passages",
    "fanlink": "lnk.bayzamusic.com/thumbs",
    "description": "This is the instrumental version of \"<a class=\"text-white\" href=\"https://bayzamusic.com/releases/2021/thumbs\" target=\"_blank\" title=\"Sabrina Carpenter - Thumbs (Bayza Bootleg)\">Sabrina Carpenter - Thumbs (Bayza Bootleg)</a>\"",
    "title": "Thumbs - Instrumental",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "passages",
    "label": null,
    "duration": "3:23",
    "video": "9u_UwD-WpSE",
    "year": 2021,
    "date": "2021-12-30 00:00:05",
    "release": "thumbs",
    "genre": "Deep House"
  },
  {
    "album": "Passages",
    "fanlink": "lnk.bayzamusic.com/Passages",
    "description": "To end the year, I decided to release an original track within an EP that also includes instrumentals of some of my previous bootlegs.",
    "title": "Passages",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "passages",
    "label": null,
    "duration": "3:00",
    "video": "gqnAPRtTnSs",
    "year": 2021,
    "date": "2021-12-30 00:00:06",
    "release": "passages",
    "genre": "Deep House"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/ImFalling",
    "description": null,
    "title": "I'm Falling",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "im-falling",
    "label": "DeepShine Records",
    "duration": "3:32",
    "video": "EZodqty3HLA",
    "year": 2022,
    "date": "2022-01-21 00:00:00",
    "release": "im-falling",
    "genre": "Deep House"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/CallOut",
    "description": null,
    "title": "Call Out",
    "type": "Releases",
    "artists": "Dimatis, Bayza",
    "cover": "call-out",
    "label": null,
    "duration": "3:40",
    "video": "vlU7crlYW4I",
    "year": 2022,
    "date": "2022-02-25 00:00:01",
    "release": "call-out",
    "genre": "Electropop"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/Pieces",
    "description": null,
    "title": "Pieces",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "pieces",
    "label": null,
    "duration": "3:03",
    "video": "VTscrLkd20s",
    "year": 2022,
    "date": "2022-05-06 00:00:00",
    "release": "pieces",
    "genre": "Dance"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/ShowMe",
    "description": null,
    "title": "Show Me What You Feel",
    "type": "Releases",
    "artists": "dbeet, Bayza",
    "cover": "show-me-what-you-feel",
    "label": "Melodicity Records",
    "duration": "2:44",
    "video": "trdqaqZCVEU",
    "year": 2022,
    "date": "2022-06-10 00:00:00",
    "release": "show-me",
    "genre": "Dance"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/YoungFree",
    "description": null,
    "title": "Young & Free",
    "type": "Releases",
    "artists": "DJ Phellix, Bayza",
    "cover": "young-free",
    "label": "Miami Beats",
    "duration": "3:23",
    "video": "-vVutcvq5I4",
    "year": 2022,
    "date": "2022-07-08 00:00:00",
    "release": "young-free",
    "genre": "Tropical House"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/WhyCantItBe",
    "description": null,
    "title": "Why Can't It Be With Me",
    "type": "Releases",
    "artists": "AMiR, Bayza",
    "cover": "why-cant-it-be",
    "label": "Storm Music Group",
    "duration": "2:58",
    "video": "BRRXzu2Q1-g",
    "year": 2022,
    "date": "2022-08-05 00:00:00",
    "release": "why-cant-it-be",
    "genre": "Dance"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/OnYourMind",
    "description": null,
    "title": "On Your Mind",
    "type": "Releases",
    "artists": "DJ Phellix, Bayza",
    "cover": "on-your-mind",
    "label": "Different Twins/Twin Girls Records",
    "duration": "2:34",
    "video": "0fdvG4GRRFA",
    "year": 2022,
    "date": "2022-09-01 00:00:00",
    "release": "on-your-mind",
    "genre": "Dance"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/TrueLovers",
    "description": null,
    "title": "True Lovers",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "true-lovers",
    "label": "Mark Music Records",
    "duration": "3:01",
    "video": "_UNJ54LGdKc",
    "year": 2022,
    "date": "2022-11-04 00:00:00",
    "release": "true-lovers",
    "genre": "Deep House"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/LunchboxFriends",
    "description": null,
    "title": "Lunchbox Friends",
    "type": "Releases",
    "artists": "Bayza, Staarz",
    "cover": "lunchbox-friends",
    "label": "Gangster City",
    "duration": "2:53",
    "video": "HRrD3Mj3sEY",
    "year": 2022,
    "date": "2022-12-09 00:00:00",
    "release": "lunchbox-friends",
    "genre": "Deep House"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/Madhouse",
    "description": null,
    "title": "Madhouse",
    "type": "Releases",
    "artists": "Bayza, Staarz",
    "cover": "madhouse",
    "label": "The Night Drive",
    "duration": "2:34",
    "video": "Hj_kBReLOQA",
    "year": 2023,
    "date": "2023-03-10 00:00:00",
    "release": "madhouse",
    "genre": "Deep House"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/LightComesUp",
    "description": null,
    "title": "Light Comes Up",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "light-comes-up",
    "label": "Twins Girls Records",
    "duration": "2:49",
    "video": "uesHdgS0o04",
    "year": 2023,
    "date": "2023-05-11 00:00:00",
    "release": "light-comes-up",
    "genre": "Chill House"
  },
  {
    "album": "Breeze",
    "fanlink": "lnk.bayzamusic.com/Awakening",
    "description": null,
    "title": "Awakening",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "breeze",
    "label": "",
    "duration": "2:33",
    "video": "tSEUdjq4dzs",
    "year": 2023,
    "date": "2023-07-28 00:00:00",
    "release": "awakening",
    "genre": "Big Room"
  },
  {
    "album": "Breeze",
    "fanlink": "lnk.bayzamusic.com/Fiesta",
    "description": null,
    "title": "Fiesta",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "breeze",
    "label": "",
    "duration": "3:42",
    "video": "uXM19g7wyFk",
    "year": 2023,
    "date": "2023-07-28 00:00:01",
    "release": "fiesta",
    "genre": "Melbourne Bounce"
  },
  {
    "album": "Breeze",
    "fanlink": "lnk.bayzamusic.com/Zenith",
    "description": null,
    "title": "Zenith",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "breeze",
    "label": "",
    "duration": "2:13",
    "video": "h6rcysVZIBI",
    "year": 2023,
    "date": "2023-07-28 00:00:02",
    "release": "zenith",
    "genre": "Psytrance"
  },
  {
    "album": "Breeze",
    "fanlink": "lnk.bayzamusic.com/Eclipse",
    "description": null,
    "title": "Eclipse",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "breeze",
    "label": "",
    "duration": "3:00",
    "video": "LGAtjLR89dU",
    "year": 2023,
    "date": "2023-07-28 00:00:03",
    "release": "eclipse",
    "genre": "Deep House"
  },
  {
    "album": "Breeze",
    "fanlink": "lnk.bayzamusic.com/ImmortalLove",
    "description": null,
    "title": "Immortal Love",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "breeze",
    "label": "",
    "duration": "3:16",
    "video": "16xwnEkR8tA",
    "year": 2023,
    "date": "2023-07-28 00:00:04",
    "release": "immortal-love",
    "genre": "Deep House"
  },
  {
    "album": "Breeze",
    "fanlink": "lnk.bayzamusic.com/Breeze",
    "description": null,
    "title": "Breeze",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "breeze",
    "label": "",
    "duration": "2:53",
    "video": "vIVwrWVBA2E",
    "year": 2023,
    "date": "2023-07-28 00:00:05",
    "release": "breeze",
    "genre": "Deep House"
  },
  {
    "album": "",
    "fanlink": "lnk.bayzamusic.com/NowOrNever",
    "description": null,
    "title": "Now Or Never",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "now-or-never",
    "label": "DeepShine Records",
    "duration": "2:36",
    "video": "CS-AQefwkRk",
    "year": 2023,
    "date": "2023-08-11 00:00:00",
    "release": "now-or-never",
    "genre": "Deep House"
  },
  {
    "album": "",
    "fanlink": "lnk.bayzamusic.com/Obsession",
    "description": null,
    "title": "Obsession",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "obsession",
    "label": "DeepShine Records",
    "duration": "2:45",
    "video": "KNmD8d2bnp0",
    "year": 2023,
    "date": "2023-09-8 00:00:00",
    "release": "obsession",
    "genre": "Deep House"
  },
  {
    "album": "",
    "fanlink": "lnk.bayzamusic.com/Redemption",
    "description": null,
    "title": "Redemption",
    "type": "Releases",
    "artists": "Bayza",
    "cover": "redemption",
    "label": "",
    "duration": "2:48",
    "video": "bk_08D0S2fI",
    "year": 2024,
    "date": "2024-05-17 00:00:00",
    "release": "redemption",
    "genre": "Dance"
  }
];